import type { Card, Pack } from "./card-data";

export const boosterSevenCards: Card[] = [
  { id: "bo7-mushroom-man", name: "きのこマン", cardType: "monster", kind: "植物族", attribute: "地", level: 2, atk: 800, def: 600, rarity: "N" },
  { id: "bo7-devil-dragon", name: "デビル・ドラゴン", cardType: "monster", kind: "ドラゴン族", attribute: "闇", level: 4, atk: 1500, def: 1200, rarity: "N" },
  { id: "bo7-jellyfish", name: "海月－ジェリーフィッシュ－", cardType: "monster", kind: "水族", attribute: "水", level: 4, atk: 1200, def: 1500, rarity: "N" },
  { id: "bo7-grappler", name: "グラップラー", cardType: "monster", kind: "爬虫類族", attribute: "水", level: 4, atk: 1300, def: 1200, rarity: "N" },
  { id: "bo7-megazowler", name: "メガザウラー", cardType: "monster", kind: "恐竜族", attribute: "地", level: 6, atk: 1800, def: 2000, rarity: "N" },
  { id: "bo7-castle-dark-illusions", name: "闇晦ましの城", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 4, atk: 920, def: 1930, rarity: "N", effect: true },
  { id: "bo7-dark-king-abyss", name: "闇魔界の覇王", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 5, atk: 2000, def: 1530, rarity: "N" },
  { id: "bo7-metal-guardian", name: "メタル・ガーディアン", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 5, atk: 1150, def: 2150, rarity: "N" },
  { id: "bo7-crass-clown", name: "マーダーサーカス", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 4, atk: 1350, def: 1400, rarity: "N", effect: true },
  { id: "bo7-pumpking", name: "ゴースト王－パンプキング－", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 6, atk: 1800, def: 2000, rarity: "N", effect: true },
  { id: "bo7-job-change-mirror", name: "転職の魔鏡", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 3, atk: 800, def: 1300, rarity: "N" },
  { id: "bo7-dream-clown", name: "ドリーム・ピエロ", cardType: "monster", kind: "戦士族", attribute: "地", level: 3, atk: 1200, def: 900, rarity: "N", effect: true },
  { id: "bo7-wisdom-devil", name: "悪魔の知恵", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 3, atk: 1250, def: 800, rarity: "N", effect: true },
  { id: "bo7-makenro", name: "魔天老", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 3, atk: 1000, def: 700, rarity: "N" },
  { id: "bo7-ancient-sorcerer", name: "古代魔導士", cardType: "monster", kind: "魔法使い族", attribute: "闇", level: 4, atk: 1000, def: 1300, rarity: "N" },
  { id: "bo7-aile-swordsman", name: "アイルの小剣士", cardType: "monster", kind: "戦士族", attribute: "水", level: 3, atk: 800, def: 1300, rarity: "N", effect: true },
  { id: "bo7-moon-envoy", name: "月の使者", cardType: "monster", kind: "戦士族", attribute: "光", level: 4, atk: 1100, def: 1000, rarity: "N" },
  { id: "bo7-giant-spider", name: "地雷蜘蛛", cardType: "monster", kind: "昆虫族", attribute: "地", level: 4, atk: 2200, def: 100, rarity: "N", effect: true },
  { id: "bo7-monster-tamer", name: "地獄の魔物使い", cardType: "monster", kind: "戦士族", attribute: "地", level: 5, atk: 1800, def: 1600, rarity: "N" },
  { id: "bo7-powered-gargoyle", name: "ガーゴイル・パワード", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 4, atk: 1600, def: 1200, rarity: "N" },
  { id: "bo7-fiend-box", name: "デビル・ボックス", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 7, atk: 2300, def: 2000, rarity: "N", fusion: true },
  { id: "bo7-blocker", name: "ブロッカー", cardType: "monster", kind: "機械族", attribute: "闇", level: 4, atk: 850, def: 1800, rarity: "N" },
  { id: "bo7-stone-dragon", name: "ストーン・ドラゴン", cardType: "monster", kind: "岩石族", attribute: "地", level: 7, atk: 2000, def: 2300, rarity: "N" },
  { id: "bo7-beautiful-beast-trainer", name: "美しき魔物使い", cardType: "monster", kind: "戦士族", attribute: "地", level: 5, atk: 1750, def: 1500, rarity: "N" },
  { id: "bo7-millennium-golem", name: "千年ゴーレム", cardType: "monster", kind: "岩石族", attribute: "地", level: 6, atk: 2000, def: 2200, rarity: "N" },
  { id: "bo7-flying-insect-soldier", name: "空の昆虫兵", cardType: "monster", kind: "昆虫族", attribute: "風", level: 3, atk: 1000, def: 800, rarity: "N", effect: true },
  { id: "bo7-yado-karu", name: "ヤドカリュー", cardType: "monster", kind: "水族", attribute: "水", level: 4, atk: 900, def: 1700, rarity: "N", effect: true },
  { id: "bo7-devil-cook", name: "悪魔の調理師", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 4, atk: 1800, def: 1000, rarity: "N", effect: true },
  { id: "bo7-night-lizard", name: "ナイト・リザード", cardType: "monster", kind: "水族", attribute: "水", level: 4, atk: 1150, def: 1300, rarity: "N" },
  { id: "bo7-skull-bishop", name: "スカルビショップ", cardType: "monster", kind: "魔法使い族", attribute: "闇", level: 7, atk: 2650, def: 2250, rarity: "N", fusion: true },
  { id: "bo7-magnetic-ring", name: "磁力の指輪", cardType: "spell", kind: "装備魔法", rarity: "N" },
  { id: "bo7-share-pain", name: "痛み分け", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "bo7-doping", name: "ドーピング", cardType: "spell", kind: "装備魔法", rarity: "N" },
  { id: "bo7-heavy-storm", name: "大嵐", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "bo7-griffin-wing", name: "グリフォンの翼", cardType: "trap", kind: "通常罠", rarity: "N" },
];

export const boosterSevenPack: Pack = {
  id: "booster-7",
  name: "Booster 7",
  releaseDate: "2000-03-01",
  category: "official",
  cardIds: [
    ...boosterSevenCards.map((card) => card.id),
    "vol7-sword-queen", "vol7-tremendous-fire", "vol7-thunder-dragon", "vol7-germ-infection", "vol7-paralyzing-potion",
  ],
};
