import type { Card, Pack } from "./card-data";

export const boosterTwoCards: Card[] = [
  { id: "bo2-blood-sucker", name: "吸血ノミ", cardType: "monster", kind: "昆虫族", attribute: "地", level: 4, atk: 1500, def: 1200, rarity: "N" },
  { id: "bo2-wood-clown", name: "ウッド・ジョーカー", cardType: "monster", kind: "戦士族", attribute: "地", level: 3, atk: 800, def: 1200, rarity: "N" },
  { id: "bo2-soul-hunter", name: "魂を狩る者", cardType: "monster", kind: "獣戦士族", attribute: "地", level: 4, atk: 1100, def: 1000, rarity: "N" },
  { id: "bo2-fairywitch", name: "エンジェル・魔女", cardType: "monster", kind: "魔法使い族", attribute: "闇", level: 3, atk: 800, def: 1000, rarity: "N" },
  { id: "bo2-megirus-light", name: "メギラス・ライト", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 3, atk: 900, def: 600, rarity: "N" },
  { id: "bo2-bat", name: "バット", cardType: "monster", kind: "機械族", attribute: "風", level: 1, atk: 300, def: 350, rarity: "N" },
  { id: "bo2-white-dolphin", name: "ホワイト・ドルフィン", cardType: "monster", kind: "魚族", attribute: "水", level: 2, atk: 500, def: 400, rarity: "N" },
  { id: "bo2-zarigun", name: "ザリガン", cardType: "monster", kind: "水族", attribute: "水", level: 2, atk: 600, def: 700, rarity: "N" },
  { id: "bo2-stone-ghost", name: "ストーン・ゴースト", cardType: "monster", kind: "岩石族", attribute: "地", level: 4, atk: 1200, def: 1000, rarity: "N" },
  { id: "bo2-bolt-penguin", name: "ボルト・ペンギン", cardType: "monster", kind: "雷族", attribute: "水", level: 3, atk: 1100, def: 800, rarity: "N" },
  { id: "bo2-insection", name: "インセクション", cardType: "monster", kind: "昆虫族", attribute: "地", level: 3, atk: 950, def: 700, rarity: "N" },
  { id: "bo2-bookoo", name: "ブークー", cardType: "monster", kind: "魔法使い族", attribute: "闇", level: 2, atk: 650, def: 500, rarity: "N" },
  { id: "bo2-wilmee", name: "ウィルミー", cardType: "monster", kind: "獣族", attribute: "地", level: 4, atk: 1000, def: 1200, rarity: "N" },
  { id: "bo2-bean-soldier", name: "ビーン・ソルジャー", cardType: "monster", kind: "植物族", attribute: "地", level: 4, atk: 1400, def: 1300, rarity: "N" },
  { id: "bo2-moai", name: "イースター島のモアイ", cardType: "monster", kind: "岩石族", attribute: "地", level: 4, atk: 1100, def: 1400, rarity: "N" },
  { id: "bo2-dead-shark", name: "デッド・シャーク", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 3, atk: 1100, def: 700, rarity: "N" },
  { id: "bo2-fish-warrior", name: "魚ギョ戦士", cardType: "monster", kind: "魚族", attribute: "水", level: 4, atk: 1250, def: 900, rarity: "N" },
  { id: "bo2-bone-mouse", name: "骨ネズミ", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 1, atk: 400, def: 300, rarity: "N" },
  { id: "bo2-wyvern", name: "ワイバーン", cardType: "monster", kind: "鳥獣族", attribute: "風", level: 4, atk: 1200, def: 1000, rarity: "N" },
  { id: "bo2-oshiro-hero", name: "オシロ・ヒーロー", cardType: "monster", kind: "戦士族", attribute: "地", level: 3, atk: 1250, def: 700, rarity: "N" },
  { id: "bo2-baby-t-rex", name: "ベビー・ティーレックス", cardType: "monster", kind: "恐竜族", attribute: "地", level: 3, atk: 1100, def: 700, rarity: "N" },
  { id: "bo2-abyss-flower", name: "深淵に咲く花", cardType: "monster", kind: "植物族", attribute: "地", level: 2, atk: 750, def: 400, rarity: "N" },
  { id: "bo2-rock-mace", name: "ロックメイス", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 4, atk: 1050, def: 1200, rarity: "N" },
  { id: "bo2-evil-rat", name: "イビル・ラット", cardType: "monster", kind: "獣族", attribute: "地", level: 3, atk: 750, def: 800, rarity: "N" },
  { id: "bo2-friendship", name: "フレンドシップ", cardType: "monster", kind: "天使族", attribute: "光", level: 4, atk: 1300, def: 1100, rarity: "N" },
  { id: "bo2-dark-piercing-sword", name: "闇の破神剣", cardType: "spell", kind: "装備魔法", rarity: "N" },
  { id: "bo2-elf-light", name: "エルフの光", cardType: "spell", kind: "装備魔法", rarity: "N" },
  { id: "bo2-steel-shell", name: "はがねの甲羅", cardType: "spell", kind: "装備魔法", rarity: "N" },
  { id: "bo2-awakening", name: "覚醒", cardType: "spell", kind: "装備魔法", rarity: "N" },
  { id: "bo2-angel-blood", name: "天使の生き血", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "bo2-fire", name: "昼夜の大火事", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "bo2-light-reveal", name: "闇をかき消す光", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "bo2-burning-spear", name: "灼熱の槍", cardType: "spell", kind: "装備魔法", rarity: "N" },
  { id: "bo2-gust-fan", name: "突風の扇", cardType: "spell", kind: "装備魔法", rarity: "N" },
  { id: "bo2-amateur-spy", name: "未熟な密偵", cardType: "spell", kind: "通常魔法", rarity: "N" },
];

export const boosterTwoPack: Pack = {
  id: "booster-2",
  name: "Booster 2",
  releaseDate: "1999-05-25",
  category: "official",
  cardIds: [
    "vol3-rogue-doll", "bo2-blood-sucker", "vol3-ansatsu", "vol3-akihiron", "vol3-mabarrel",
    "bo2-wood-clown", "bo2-soul-hunter", "bo2-fairywitch", "bo2-megirus-light",
    "bo2-dark-piercing-sword", "bo2-elf-light", "bo2-steel-shell", "bo2-awakening",
    "bo2-angel-blood", "bo2-fire", "bo2-light-reveal", "vol3-giant-mech-soldier",
    "bo2-bat", "bo2-white-dolphin", "bo2-zarigun", "bo2-stone-ghost", "bo2-bolt-penguin",
    "bo2-insection", "bo2-bookoo", "bo2-wilmee", "bo2-bean-soldier", "bo2-moai",
    "bo2-dead-shark", "bo2-fish-warrior", "bo2-bone-mouse", "bo2-wyvern", "bo2-oshiro-hero",
    "bo2-baby-t-rex", "bo2-abyss-flower", "bo2-rock-mace", "bo2-evil-rat", "bo2-friendship",
    "bo2-burning-spear", "bo2-gust-fan", "bo2-amateur-spy",
  ],
};
