import type { Card, Pack } from "./card-data";

export const boosterFiveCards: Card[] = [
  { id: "bo5-two-headed-king-rex", name: "二頭を持つキング・レックス", cardType: "monster", kind: "恐竜族", attribute: "地", level: 4, atk: 1600, def: 1200, rarity: "N" },
  { id: "bo5-medusa-ghost", name: "メデューサの亡霊", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 4, atk: 1500, def: 1200, rarity: "N" },
  { id: "bo5-wolf", name: "オオカミ", cardType: "monster", kind: "獣族", attribute: "地", level: 3, atk: 1200, def: 800, rarity: "N" },
  { id: "bo5-crocodilus", name: "クロコダイラス", cardType: "monster", kind: "爬虫類族", attribute: "水", level: 4, atk: 1100, def: 1200, rarity: "N" },
  { id: "bo5-crawling-dragon-2", name: "屍を貪る竜", cardType: "monster", kind: "恐竜族", attribute: "地", level: 4, atk: 1600, def: 1200, rarity: "N" },
  { id: "bo5-dragon-zombie", name: "ドラゴン・ゾンビ", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 3, atk: 1600, def: 0, rarity: "N" },
  { id: "bo5-genie-lamp", name: "ランプの魔人", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 4, atk: 1400, def: 1200, rarity: "N" },
  { id: "bo5-mysterious-puppeteer", name: "謎の傀儡師", cardType: "monster", kind: "戦士族", attribute: "地", level: 4, atk: 1000, def: 1500, rarity: "N", effect: true },
  { id: "bo5-trap-master", name: "トラップ・マスター", cardType: "monster", kind: "戦士族", attribute: "地", level: 3, atk: 500, def: 1100, rarity: "N", effect: true },
  { id: "bo5-weather-control", name: "ウェザ", cardType: "monster", kind: "水族", attribute: "水", level: 3, atk: 1000, def: 900, rarity: "N" },
  { id: "bo5-dungeon-worm", name: "ダンジョン・ワーム", cardType: "monster", kind: "昆虫族", attribute: "地", level: 5, atk: 1800, def: 1500, rarity: "R" },
  { id: "bo5-rude-kaiser", name: "ルード・カイザー", cardType: "monster", kind: "獣戦士族", attribute: "地", level: 5, atk: 1800, def: 1600, rarity: "R" },
  { id: "bo5-machine-king", name: "機械王", cardType: "monster", kind: "機械族", attribute: "地", level: 6, atk: 2200, def: 2000, rarity: "N", effect: true },
  { id: "bo5-water-magician", name: "水の魔導師", cardType: "monster", kind: "水族", attribute: "水", level: 4, atk: 1400, def: 1000, rarity: "N" },
  { id: "bo5-aqua-snake", name: "アクア・スネーク", cardType: "monster", kind: "水族", attribute: "水", level: 3, atk: 1050, def: 900, rarity: "N" },
  { id: "bo5-white-turtle", name: "３万年の白亀", cardType: "monster", kind: "水族", attribute: "水", level: 5, atk: 1250, def: 2100, rarity: "N" },
  { id: "bo5-wing-eagle", name: "ウイング・イーグル", cardType: "monster", kind: "鳥獣族", attribute: "風", level: 5, atk: 1800, def: 1500, rarity: "N" },
  { id: "bo5-soul-hunter", name: "ソウル・ハンター", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 6, atk: 2200, def: 1800, rarity: "N", fusion: true },
  { id: "bo5-korogashi", name: "コロガーシ", cardType: "monster", kind: "昆虫族", attribute: "地", level: 2, atk: 550, def: 400, rarity: "N" },
  { id: "bo5-needle-ball", name: "ニードル・ボール", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 2, atk: 750, def: 700, rarity: "N", effect: true },
  { id: "bo5-rainbow-mermaid", name: "レインボー・マリン・マーメイド", cardType: "monster", kind: "魚族", attribute: "水", level: 5, atk: 1550, def: 1700, rarity: "N" },
  { id: "bo5-dragon-killer", name: "竜殺者", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 6, atk: 2000, def: 2100, rarity: "N", effect: true },
  { id: "bo5-turtle-raccoon", name: "タートル・狸", cardType: "monster", kind: "水族", attribute: "水", level: 3, atk: 700, def: 900, rarity: "N" },
  { id: "bo5-demon-plant", name: "魔界植物", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 1, atk: 400, def: 300, rarity: "N" },
  { id: "bo5-brachio-raidus", name: "ブラキオレイドス", cardType: "monster", kind: "恐竜族", attribute: "水", level: 6, atk: 2200, def: 2000, rarity: "N", fusion: true },
  { id: "bo5-behegon", name: "ベヒゴン", cardType: "monster", kind: "水族", attribute: "水", level: 4, atk: 1350, def: 1000, rarity: "N" },
  { id: "bo5-pot-trick", name: "ポット・ザ・トリック", cardType: "monster", kind: "岩石族", attribute: "地", level: 2, atk: 400, def: 400, rarity: "N" },
  { id: "bo5-invader-another-dimension", name: "異次元からの侵略者", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 4, atk: 950, def: 1400, rarity: "N" },
  { id: "bo5-needle-worm", name: "ニードルワーム", cardType: "monster", kind: "昆虫族", attribute: "地", level: 2, atk: 750, def: 600, rarity: "N", effect: true },
  { id: "bo5-golden-elephant", name: "金色の魔象", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 6, atk: 2200, def: 1800, rarity: "N", fusion: true },
  { id: "bo5-crow-tengu", name: "カラス天狗", cardType: "monster", kind: "鳥獣族", attribute: "風", level: 5, atk: 1850, def: 1600, rarity: "R" },
  { id: "bo5-tentacle-plant", name: "テンタクル・プラント", cardType: "monster", kind: "植物族", attribute: "水", level: 2, atk: 500, def: 600, rarity: "N" },
  { id: "bo5-beaked-snake", name: "くちばしヘビ", cardType: "monster", kind: "爬虫類族", attribute: "地", level: 3, atk: 800, def: 900, rarity: "N" },
  { id: "bo5-morphing-jar", name: "メタモルポット", cardType: "monster", kind: "岩石族", attribute: "地", level: 2, atk: 700, def: 600, rarity: "N", effect: true },
  { id: "bo5-marine-beast", name: "マリン・ビースト", cardType: "monster", kind: "魚族", attribute: "水", level: 5, atk: 1700, def: 1600, rarity: "N", fusion: true },
  { id: "bo5-machine-attacker", name: "マシン・アタッカー", cardType: "monster", kind: "機械族", attribute: "地", level: 5, atk: 1600, def: 1300, rarity: "N" },
  { id: "bo5-just-desserts", name: "自業自得", cardType: "trap", kind: "通常罠", rarity: "N" },
  { id: "bo5-royal-decree", name: "王宮のお触れ", cardType: "trap", kind: "永続罠", rarity: "N" },
];

export const boosterFivePack: Pack = {
  id: "booster-5",
  name: "Booster 5",
  releaseDate: "1999-10-17",
  category: "official",
  cardIds: [
    ...boosterFiveCards.map((card) => card.id),
    "vol5-anti-raigeki", "vol5-call-darkness",
  ],
};
