import type { Card, Pack } from "./card-data";

export const boosterThreeCards: Card[] = [
  { id: "bo3-hercules-beetle", name: "ヘラクレス・ビートル", cardType: "monster", kind: "昆虫族", attribute: "地", level: 5, atk: 1500, def: 2000, rarity: "N" },
  { id: "bo3-great-white", name: "グレート・ホワイト", cardType: "monster", kind: "魚族", attribute: "水", level: 4, atk: 1600, def: 800, rarity: "N" },
  { id: "bo3-tiger-axe", name: "タイガー・アックス", cardType: "monster", kind: "獣戦士族", attribute: "地", level: 4, atk: 1300, def: 1100, rarity: "N" },
  { id: "bo3-soul-hunter", name: "命を食する者", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 4, atk: 1200, def: 1000, rarity: "N" },
  { id: "bo3-hawk-bishop", name: "本の精霊 ホーク・ビショップ", cardType: "monster", kind: "鳥獣族", attribute: "風", level: 4, atk: 1400, def: 1200, rarity: "N" },
  { id: "bo3-la-moon", name: "ラムーン", cardType: "monster", kind: "魔法使い族", attribute: "光", level: 5, atk: 1200, def: 1700, rarity: "N" },
  { id: "bo3-skull-temple", name: "髑髏の寺院", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 4, atk: 900, def: 1300, rarity: "N" },
  { id: "bo3-raimundos", name: "赤き剣のライムンドス", cardType: "monster", kind: "戦士族", attribute: "地", level: 4, atk: 1200, def: 1300, rarity: "N" },
  { id: "bo3-sapphire-lisark", name: "サファイヤ・リサーク", cardType: "monster", kind: "獣族", attribute: "地", level: 4, atk: 1300, def: 1300, rarity: "N" },
  { id: "bo3-judgment-hand", name: "ジャジメント・ザ・ハンド", cardType: "monster", kind: "戦士族", attribute: "地", level: 3, atk: 1400, def: 700, rarity: "N" },
  { id: "bo3-dryad", name: "ドリアード", cardType: "monster", kind: "魔法使い族", attribute: "地", level: 4, atk: 1200, def: 1400, rarity: "N" },
  { id: "bo3-headless-beauty", name: "斬首の美女", cardType: "monster", kind: "戦士族", attribute: "地", level: 4, atk: 1600, def: 800, rarity: "N" },
  { id: "bo3-udan", name: "森の住人 ウダン", cardType: "monster", kind: "戦士族", attribute: "地", level: 3, atk: 900, def: 1200, rarity: "N", effect: true },
  { id: "bo3-palm-tree", name: "ヤシの木", cardType: "monster", kind: "植物族", attribute: "地", level: 2, atk: 800, def: 600, rarity: "N" },
  { id: "bo3-berserker", name: "バーサーカー", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 4, atk: 1500, def: 1000, rarity: "N" },
  { id: "bo3-dark-artist", name: "闇の芸術家", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 3, atk: 600, def: 1400, rarity: "N", effect: true },
  { id: "bo3-machine-soldier", name: "魔界の機械兵", cardType: "monster", kind: "機械族", attribute: "闇", level: 4, atk: 1400, def: 1200, rarity: "N" },
  { id: "bo3-otome", name: "音女", cardType: "monster", kind: "戦士族", attribute: "地", level: 3, atk: 1200, def: 900, rarity: "N" },
  { id: "bo3-seahorse", name: "シーホース", cardType: "monster", kind: "獣族", attribute: "地", level: 5, atk: 1350, def: 1600, rarity: "N" },
  { id: "bo3-golgoil", name: "ゴルゴイル", cardType: "monster", kind: "機械族", attribute: "地", level: 4, atk: 900, def: 1600, rarity: "N" },
  { id: "bo3-kappa-avenger", name: "復讐のカッパ", cardType: "monster", kind: "水族", attribute: "水", level: 3, atk: 1200, def: 900, rarity: "N" },
  { id: "bo3-rock-soldier", name: "岩の戦士", cardType: "monster", kind: "岩石族", attribute: "地", level: 4, atk: 1300, def: 1200, rarity: "N" },
  { id: "bo3-vermillion-sparrow", name: "朱雀", cardType: "monster", kind: "炎族", attribute: "炎", level: 5, atk: 1900, def: 1500, rarity: "N", fusion: true },
  { id: "bo3-kuwagata-alpha", name: "クワガタ・アルファ", cardType: "monster", kind: "昆虫族", attribute: "地", level: 4, atk: 1250, def: 1000, rarity: "N" },
  { id: "bo3-death-bird", name: "デス・バード", cardType: "monster", kind: "鳥獣族", attribute: "風", level: 6, atk: 1900, def: 1700, rarity: "N", fusion: true },
  { id: "bo3-kwagar-hercules", name: "クワガー・ヘラクレス", cardType: "monster", kind: "昆虫族", attribute: "地", level: 6, atk: 1900, def: 1700, rarity: "N", fusion: true },
  { id: "bo3-jormungard", name: "ヨルムンガルド", cardType: "monster", kind: "爬虫類族", attribute: "地", level: 3, atk: 1200, def: 900, rarity: "N" },
  { id: "bo3-leo-wizard", name: "レオ・ウィザード", cardType: "monster", kind: "魔法使い族", attribute: "地", level: 5, atk: 1350, def: 1200, rarity: "N" },
  { id: "bo3-patrol-robo", name: "パトロール・ロボ", cardType: "monster", kind: "機械族", attribute: "地", level: 3, atk: 1100, def: 900, rarity: "N", effect: true },
  { id: "bo3-takuhee", name: "タクヒ", cardType: "monster", kind: "鳥獣族", attribute: "風", level: 4, atk: 1450, def: 1000, rarity: "N" },
  { id: "bo3-mon-larvas", name: "モン・ラーバス", cardType: "monster", kind: "獣族", attribute: "地", level: 4, atk: 1300, def: 1400, rarity: "N" },
  { id: "bo3-living-vase", name: "命ある花瓶", cardType: "monster", kind: "植物族", attribute: "地", level: 3, atk: 900, def: 1100, rarity: "N" },
  { id: "bo3-muse-a", name: "ミューズの天使", cardType: "monster", kind: "天使族", attribute: "光", level: 3, atk: 850, def: 900, rarity: "N" },
  { id: "bo3-hourglass-courage", name: "勇気の砂時計", cardType: "monster", kind: "天使族", attribute: "光", level: 4, atk: 1100, def: 1200, rarity: "R", effect: true },
  { id: "bo3-warrior-elimination", name: "戦場の死装束", cardType: "monster", kind: "戦士族", attribute: "地", level: 6, atk: 1900, def: 1700, rarity: "N", fusion: true },
  { id: "bo3-reverse-trap", name: "あまのじゃくの呪い", cardType: "trap", kind: "通常罠", rarity: "R" },
  { id: "bo3-reinforcements", name: "援軍", cardType: "trap", kind: "通常罠", rarity: "R" },
  { id: "bo3-castle-walls", name: "城壁", cardType: "trap", kind: "通常罠", rarity: "R" },
  { id: "bo3-ultimate-offering", name: "血の代償", cardType: "trap", kind: "永続罠", rarity: "R" },
  { id: "bo3-ancient-telescope", name: "古代の遠眼鏡", cardType: "spell", kind: "通常魔法", rarity: "N" },
];

export const boosterThreePack: Pack = {
  id: "booster-3",
  name: "Booster 3",
  releaseDate: "1999-07-17",
  category: "official",
  cardIds: boosterThreeCards.map((card) => card.id),
};
