import type { Card, Pack } from "./card-data";

export const boosterSixCards: Card[] = [
  { id: "bo6-sword-dragon", name: "剣竜", cardType: "monster", kind: "恐竜族", attribute: "地", level: 6, atk: 1750, def: 2030, rarity: "N" },
  { id: "bo6-battle-ox", name: "ミノタウルス", cardType: "monster", kind: "獣戦士族", attribute: "地", level: 4, atk: 1700, def: 1000, rarity: "N" },
  { id: "bo6-garoozis", name: "ガルーザス", cardType: "monster", kind: "獣戦士族", attribute: "炎", level: 5, atk: 1800, def: 1500, rarity: "N" },
  { id: "bo6-kairyu-shin", name: "海竜神", cardType: "monster", kind: "海竜族", attribute: "水", level: 5, atk: 1800, def: 1500, rarity: "N" },
  { id: "bo6-spirit-winds", name: "風の精霊", cardType: "monster", kind: "魔法使い族", attribute: "風", level: 5, atk: 1700, def: 1400, rarity: "N" },
  { id: "bo6-goddess-third-eye", name: "心眼の女神", cardType: "monster", kind: "天使族", attribute: "光", level: 4, atk: 1200, def: 1000, rarity: "N", effect: true },
  { id: "bo6-dragon-statue", name: "竜魂の石像", cardType: "monster", kind: "戦士族", attribute: "地", level: 3, atk: 1100, def: 900, rarity: "N" },
  { id: "bo6-swamp-beast-king", name: "沼地の魔獣王", cardType: "monster", kind: "水族", attribute: "水", level: 4, atk: 1000, def: 1100, rarity: "N", effect: true },
  { id: "bo6-versago-destroyer", name: "破壊神 ヴァサーゴ", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 3, atk: 1100, def: 900, rarity: "N", effect: true },
  { id: "bo6-parrot-dragon", name: "パロット・ドラゴン", cardType: "monster", kind: "ドラゴン族", attribute: "風", level: 5, atk: 2000, def: 1300, rarity: "N" },
  { id: "bo6-ushioni", name: "牛鬼", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 6, atk: 2150, def: 1950, rarity: "N" },
  { id: "bo6-monster-eye", name: "モンスター・アイ", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 1, atk: 250, def: 350, rarity: "N", effect: true },
  { id: "bo6-cyber-stein", name: "デビル・フランケン", cardType: "monster", kind: "機械族", attribute: "闇", level: 2, atk: 700, def: 500, rarity: "N", effect: true },
  { id: "bo6-sky-dragon", name: "天空竜", cardType: "monster", kind: "ドラゴン族", attribute: "風", level: 6, atk: 1900, def: 1800, rarity: "N" },
  { id: "bo6-kaiser-dragon", name: "カイザー・ドラゴン", cardType: "monster", kind: "ドラゴン族", attribute: "光", level: 7, atk: 2300, def: 2000, rarity: "N", fusion: true },
  { id: "bo6-sea-guardian", name: "海を守る戦士", cardType: "monster", kind: "水族", attribute: "水", level: 4, atk: 1300, def: 1000, rarity: "N" },
  { id: "bo6-crimson-sunbird", name: "紅陽鳥", cardType: "monster", kind: "鳥獣族", attribute: "炎", level: 6, atk: 2300, def: 1800, rarity: "N", fusion: true },
  { id: "bo6-garvas", name: "ガルヴァス", cardType: "monster", kind: "獣族", attribute: "地", level: 6, atk: 2000, def: 1700, rarity: "N" },
  { id: "bo6-gale-dogra", name: "ゲール・ドグラ", cardType: "monster", kind: "昆虫族", attribute: "地", level: 2, atk: 650, def: 600, rarity: "N", effect: true },
  { id: "bo6-rock-turtle", name: "岩石カメッター", cardType: "monster", kind: "水族", attribute: "水", level: 6, atk: 1450, def: 2200, rarity: "N" },
  { id: "bo6-neck-hunter", name: "首狩り魔人", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 6, atk: 1750, def: 1900, rarity: "N" },
  { id: "bo6-sand-witch", name: "砂の魔女", cardType: "monster", kind: "岩石族", attribute: "地", level: 6, atk: 2100, def: 1700, rarity: "N", fusion: true },
  { id: "bo6-mechaleon", name: "メカレオン", cardType: "monster", kind: "爬虫類族", attribute: "水", level: 2, atk: 800, def: 600, rarity: "N" },
  { id: "bo6-skelgon", name: "スケルゴン", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 6, atk: 1700, def: 1900, rarity: "N", fusion: true },
  { id: "bo6-doppelganger", name: "ドッペルゲンガー", cardType: "monster", kind: "戦士族", attribute: "闇", level: 3, atk: 650, def: 900, rarity: "N", effect: true },
  { id: "bo6-penguin-soldier", name: "ペンギン・ソルジャー", cardType: "monster", kind: "水族", attribute: "水", level: 2, atk: 750, def: 500, rarity: "N", effect: true },
  { id: "bo6-rock-spirit", name: "岩石の精霊", cardType: "monster", kind: "魔法使い族", attribute: "地", level: 5, atk: 1650, def: 1900, rarity: "N" },
  { id: "bo6-siren", name: "セイレーン", cardType: "monster", kind: "魔法使い族", attribute: "光", level: 5, atk: 1600, def: 1500, rarity: "N" },
  { id: "bo6-amphibious-bugroth", name: "水陸両用バグロス", cardType: "monster", kind: "水族", attribute: "水", level: 5, atk: 1850, def: 1300, rarity: "N", fusion: true },
  { id: "bo6-illusion-sheep", name: "イリュージョン・シープ", cardType: "monster", kind: "獣族", attribute: "地", level: 3, atk: 1150, def: 900, rarity: "N", effect: true },
  { id: "bo6-witch-hunt", name: "魔女狩り", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "bo6-exile-wicked", name: "悪魔払い", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "bo6-magic-thorn", name: "魔力の棘", cardType: "trap", kind: "永続罠", rarity: "N" },
  { id: "bo6-revolution", name: "革命", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "bo6-fusion-sage", name: "融合賢者", cardType: "spell", kind: "通常魔法", rarity: "N" },
];

export const boosterSixPack: Pack = {
  id: "booster-6",
  name: "Booster 6",
  releaseDate: "1999-12-01",
  category: "official",
  cardIds: [
    ...boosterSixCards.map((card) => card.id),
    "vol6-hoshiningen", "vol6-star-boy", "vol6-little-chimera", "vol6-bladefly", "vol6-witch-apprentice",
  ],
};
