import type { Card, Pack } from "./card-data";

export const boosterFourCards: Card[] = [
  { id: "bo4-worm-beast", name: "邪悪なるワーム・ビースト", cardType: "monster", kind: "獣族", attribute: "地", level: 3, atk: 1400, def: 700, rarity: "N", effect: true },
  { id: "bo4-big-ant", name: "ビック・アント", cardType: "monster", kind: "昆虫族", attribute: "地", level: 4, atk: 1200, def: 1500, rarity: "N" },
  { id: "bo4-devil-kraken", name: "デビル・クラーケン", cardType: "monster", kind: "水族", attribute: "水", level: 4, atk: 1200, def: 1400, rarity: "N" },
  { id: "bo4-axe-raider", name: "アックス・レイダー", cardType: "monster", kind: "戦士族", attribute: "地", level: 4, atk: 1700, def: 1150, rarity: "N" },
  { id: "bo4-saint-bird", name: "セイント・バード", cardType: "monster", kind: "鳥獣族", attribute: "風", level: 4, atk: 1500, def: 1100, rarity: "N" },
  { id: "bo4-orion", name: "戦いの神 オリオン", cardType: "monster", kind: "天使族", attribute: "光", level: 5, atk: 1800, def: 1500, rarity: "N" },
  { id: "bo4-nightmare", name: "暗黒魔神 ナイトメア", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 4, atk: 1300, def: 1100, rarity: "N" },
  { id: "bo4-gorgon-egg", name: "ゴーゴン・エッグ", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 3, atk: 300, def: 1300, rarity: "N" },
  { id: "bo4-la-jinn", name: "ランプの魔精・ラ・ジーン", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 4, atk: 1800, def: 1000, rarity: "N" },
  { id: "bo4-zone-eater", name: "ゾーン・イーター", cardType: "monster", kind: "水族", attribute: "水", level: 1, atk: 250, def: 200, rarity: "N", effect: true },
  { id: "bo4-foreign-swordsman", name: "異国の剣士", cardType: "monster", kind: "戦士族", attribute: "地", level: 1, atk: 250, def: 250, rarity: "N", effect: true },
  { id: "bo4-emperor-land-sea", name: "水陸の帝王", cardType: "monster", kind: "爬虫類族", attribute: "水", level: 5, atk: 1800, def: 1500, rarity: "N" },
  { id: "bo4-mechanical-spider", name: "カラクリ蜘蛛", cardType: "monster", kind: "機械族", attribute: "地", level: 2, atk: 400, def: 500, rarity: "N", effect: true },
  { id: "bo4-mech-hunter", name: "メカ・ハンター", cardType: "monster", kind: "機械族", attribute: "闇", level: 4, atk: 1850, def: 800, rarity: "N" },
  { id: "bo4-cyber-bass", name: "サイボーグ・バス", cardType: "monster", kind: "機械族", attribute: "水", level: 5, atk: 1800, def: 1500, rarity: "N" },
  { id: "bo4-aqua-dragon", name: "アクア・ドラゴン", cardType: "monster", kind: "海竜族", attribute: "水", level: 6, atk: 2250, def: 1900, rarity: "N", fusion: true },
  { id: "bo4-sezarion", name: "シーザリオン", cardType: "monster", kind: "水族", attribute: "水", level: 4, atk: 1800, def: 800, rarity: "N" },
  { id: "bo4-gunrock", name: "ガンロック", cardType: "monster", kind: "岩石族", attribute: "地", level: 4, atk: 1000, def: 1300, rarity: "N" },
  { id: "bo4-sea-kamen", name: "シーカーメン", cardType: "monster", kind: "水族", attribute: "水", level: 4, atk: 1100, def: 1300, rarity: "N" },
  { id: "bo4-cockroach-knight", name: "コカローチ・ナイト", cardType: "monster", kind: "昆虫族", attribute: "地", level: 3, atk: 800, def: 900, rarity: "N", effect: true },
  { id: "bo4-brave-scissors", name: "ブレイブ・シザー", cardType: "monster", kind: "機械族", attribute: "闇", level: 4, atk: 1300, def: 1000, rarity: "N" },
  { id: "bo4-turtle-bird", name: "タートル・バード", cardType: "monster", kind: "水族", attribute: "水", level: 6, atk: 1900, def: 1700, rarity: "N" },
  { id: "bo4-mountain-spirit", name: "山の精霊", cardType: "monster", kind: "魔法使い族", attribute: "地", level: 5, atk: 1300, def: 1800, rarity: "N" },
  { id: "bo4-gemini-elf", name: "ヂェミナイ・エルフ", cardType: "monster", kind: "魔法使い族", attribute: "地", level: 4, atk: 1900, def: 900, rarity: "N" },
  { id: "bo4-black-shark", name: "黒き人食い鮫", cardType: "monster", kind: "魚族", attribute: "水", level: 5, atk: 2100, def: 1300, rarity: "N", fusion: true },
  { id: "bo4-fairy-dragon", name: "フェアリー・ドラゴン", cardType: "monster", kind: "ドラゴン族", attribute: "風", level: 4, atk: 1100, def: 1200, rarity: "N" },
  { id: "bo4-fountain-fairy", name: "泉の妖精", cardType: "monster", kind: "水族", attribute: "水", level: 4, atk: 1600, def: 1100, rarity: "N" },
  { id: "bo4-warrior-of-tradition", name: "海原の女戦士", cardType: "monster", kind: "魚族", attribute: "水", level: 4, atk: 1300, def: 1400, rarity: "N" },
  { id: "bo4-maiden-moonlight", name: "月明かりの乙女", cardType: "monster", kind: "魔法使い族", attribute: "光", level: 4, atk: 1500, def: 1300, rarity: "N" },
  { id: "bo4-winged-egg", name: "誕生の天使", cardType: "monster", kind: "天使族", attribute: "光", level: 5, atk: 1400, def: 1700, rarity: "N" },
  { id: "bo4-autumn-queen", name: "紅葉の女王", cardType: "monster", kind: "植物族", attribute: "地", level: 5, atk: 1800, def: 1500, rarity: "N" },
  { id: "bo4-killer-blob", name: "キラー・ブロッブ", cardType: "monster", kind: "水族", attribute: "水", level: 3, atk: 1300, def: 700, rarity: "N" },
  { id: "bo4-graceful-charity", name: "天使の施し", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "bo4-white-hole", name: "ホワイト・ホール", cardType: "trap", kind: "通常罠", rarity: "N" },
  { id: "bo4-call-grave", name: "墓場からの呼び声", cardType: "trap", kind: "通常罠", rarity: "N" },
];

export const boosterFourPack: Pack = {
  id: "booster-4",
  name: "Booster 4",
  releaseDate: "1999-08-26",
  category: "official",
  cardIds: [
    ...boosterFourCards.map((card) => card.id),
    "vol4-warrior-elimination", "vol4-acid-storm", "vol4-insecticide", "vol4-breath-god", "vol4-eternal-drought",
  ],
};
