export type Rarity = "SE" | "UR" | "SR" | "R" | "N";

export type Card = {
  id: string;
  name: string;
  cardType: "monster" | "spell" | "trap";
  kind: string;
  attribute?: string;
  level?: number;
  atk?: number;
  def?: number;
  rarity: Rarity;
  fusion?: boolean;
  effect?: boolean;
};

export type Pack = {
  id: string;
  name: string;
  releaseDate: string;
  category: "official" | "original";
  cardIds: string[];
};

export const cards: Card[] = [
  { id: "vol1-cyclops", name: "サイクロプス", cardType: "monster", kind: "獣戦士族", attribute: "地", level: 4, atk: 1200, def: 1000, rarity: "N" },
  { id: "vol1-dark-magician", name: "ブラック・マジシャン", cardType: "monster", kind: "魔法使い族", attribute: "闇", level: 7, atk: 2500, def: 2100, rarity: "UR" },
  { id: "vol1-gaia", name: "暗黒騎士ガイア", cardType: "monster", kind: "戦士族", attribute: "地", level: 7, atk: 2300, def: 2100, rarity: "UR" },
  { id: "vol1-mammoth-graveyard", name: "マンモスの墓場", cardType: "monster", kind: "恐竜族", attribute: "地", level: 3, atk: 1200, def: 800, rarity: "N" },
  { id: "vol1-silver-fang", name: "シルバー・フォング", cardType: "monster", kind: "獣族", attribute: "地", level: 3, atk: 1200, def: 800, rarity: "N" },
  { id: "vol1-curtain", name: "黒魔族のカーテン", cardType: "monster", kind: "魔法使い族", attribute: "闇", level: 2, atk: 600, def: 500, rarity: "N" },
  { id: "vol1-tomozaurus", name: "トモザウルス", cardType: "monster", kind: "恐竜族", attribute: "地", level: 2, atk: 500, def: 400, rarity: "N" },
  { id: "vol1-dark-gray", name: "ダーク・グレイ", cardType: "monster", kind: "獣族", attribute: "地", level: 3, atk: 800, def: 900, rarity: "N" },
  { id: "vol1-nemuriko", name: "眠り子", cardType: "monster", kind: "魔法使い族", attribute: "闇", level: 3, atk: 800, def: 700, rarity: "N" },
  { id: "vol1-arm-of-the-dead", name: "死者の腕", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 2, atk: 600, def: 600, rarity: "N" },
  { id: "vol1-fire-reaper", name: "ファイヤー・デビル", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 2, atk: 700, def: 500, rarity: "N" },
  { id: "vol1-firegrass", name: "火炎草", cardType: "monster", kind: "植物族", attribute: "地", level: 2, atk: 700, def: 600, rarity: "N" },
  { id: "vol1-kopix", name: "コピックス", cardType: "monster", kind: "戦士族", attribute: "地", level: 2, atk: 600, def: 500, rarity: "N" },
  { id: "vol1-lala-li-oon", name: "ララ・ライウーン", cardType: "monster", kind: "雷族", attribute: "風", level: 2, atk: 600, def: 600, rarity: "N" },
  { id: "vol1-petit-dragon", name: "プチリュウ", cardType: "monster", kind: "ドラゴン族", attribute: "風", level: 2, atk: 600, def: 700, rarity: "N" },
  { id: "vol1-archfiend-marmot", name: "デーモン・ビーバー", cardType: "monster", kind: "獣族", attribute: "地", level: 2, atk: 400, def: 600, rarity: "N" },
  { id: "vol1-petit-angel", name: "プチテンシ", cardType: "monster", kind: "天使族", attribute: "光", level: 3, atk: 600, def: 900, rarity: "N" },
  { id: "vol1-dark-killer", name: "ダークキラー", cardType: "monster", kind: "昆虫族", attribute: "地", level: 2, atk: 700, def: 700, rarity: "N" },
  { id: "vol1-thunder-kid", name: "サンダー・キッズ", cardType: "monster", kind: "雷族", attribute: "風", level: 2, atk: 700, def: 600, rarity: "N" },
  { id: "vol1-babylon", name: "バビロン", cardType: "monster", kind: "獣族", attribute: "地", level: 2, atk: 700, def: 600, rarity: "N" },
  { id: "vol1-kagemusha", name: "紫炎の影武者", cardType: "monster", kind: "戦士族", attribute: "地", level: 2, atk: 800, def: 400, rarity: "N" },
  { id: "vol1-tentacle-plant", name: "ヒトデンチャク", cardType: "monster", kind: "水族", attribute: "水", level: 2, atk: 600, def: 700, rarity: "N" },
  { id: "vol1-hourglass", name: "命の砂時計", cardType: "monster", kind: "天使族", attribute: "光", level: 2, atk: 700, def: 600, rarity: "N" },
  { id: "vol1-haniwa", name: "はにわ", cardType: "monster", kind: "岩石族", attribute: "地", level: 2, atk: 500, def: 500, rarity: "N" },
  { id: "vol1-death-foot", name: "デス・フット", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 3, atk: 700, def: 800, rarity: "N" },
  { id: "vol1-candle", name: "運命のろうそく", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 2, atk: 600, def: 600, rarity: "N" },
  { id: "vol1-demons-mirror", name: "悪魔の鏡", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 2, atk: 700, def: 600, rarity: "N" },
  { id: "vol1-angry-sea-king", name: "怒りの海王", cardType: "monster", kind: "水族", attribute: "水", level: 3, atk: 800, def: 700, rarity: "N" },
  { id: "vol1-darkness-approaches", name: "闇にしたがう者", cardType: "monster", kind: "魔法使い族", attribute: "闇", level: 2, atk: 700, def: 500, rarity: "N" },
  { id: "vol1-drake", name: "ドレイク", cardType: "monster", kind: "鳥獣族", attribute: "風", level: 3, atk: 800, def: 800, rarity: "N" },
  { id: "vol1-legendary-sword", name: "伝説の剣", cardType: "spell", kind: "装備魔法", rarity: "R" },
  { id: "vol1-beast-fangs", name: "猛獣の歯", cardType: "spell", kind: "装備魔法", rarity: "R" },
  { id: "vol1-violet-crystal", name: "紫水晶", cardType: "spell", kind: "装備魔法", rarity: "R" },
  { id: "vol1-book-secret-arts", name: "秘術の書", cardType: "spell", kind: "装備魔法", rarity: "R" },
  { id: "vol1-power-kaishin", name: "ポセイドンの力", cardType: "spell", kind: "装備魔法", rarity: "R" },
  { id: "vol1-dark-hole", name: "ブラック・ホール", cardType: "spell", kind: "通常魔法", rarity: "SR" },
  { id: "vol1-red-medicine", name: "レッド・ポーション", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "vol1-sparks", name: "火の粉", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "vol1-fissure", name: "地割れ", cardType: "spell", kind: "通常魔法", rarity: "SR" },
  { id: "vol1-trap-hole", name: "落とし穴", cardType: "trap", kind: "通常罠", rarity: "SR" },
  { id: "vol2-holy-elf", name: "ホーリー・エルフ", cardType: "monster", kind: "魔法使い族", attribute: "光", level: 4, atk: 800, def: 2000, rarity: "SR" },
  { id: "vol2-tyhone", name: "タイホーン", cardType: "monster", kind: "鳥獣族", attribute: "風", level: 4, atk: 1200, def: 1400, rarity: "N" },
  { id: "vol2-undead-warrior", name: "アンデット・ウォーリアー", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 3, atk: 1200, def: 900, rarity: "N", fusion: true },
  { id: "vol2-curse-of-dragon", name: "カース・オブ・ドラゴン", cardType: "monster", kind: "ドラゴン族", attribute: "闇", level: 5, atk: 2000, def: 1500, rarity: "UR" },
  { id: "vol2-karbonala-warrior", name: "カルボナーラ戦士", cardType: "monster", kind: "戦士族", attribute: "地", level: 4, atk: 1500, def: 1200, rarity: "N", fusion: true },
  { id: "vol2-wild-raptor", name: "ワイルド・ラプター", cardType: "monster", kind: "恐竜族", attribute: "地", level: 4, atk: 1500, def: 800, rarity: "N" },
  { id: "vol2-chaos-wizard", name: "カオス・ウィザード", cardType: "monster", kind: "魔法使い族", attribute: "闇", level: 4, atk: 1300, def: 1100, rarity: "N", fusion: true },
  { id: "vol2-supporter-shadows", name: "物陰の協力者", cardType: "monster", kind: "戦士族", attribute: "地", level: 3, atk: 1000, def: 1000, rarity: "N" },
  { id: "vol2-blue-eyed-silver-zombie", name: "青眼の銀ゾンビ", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 3, atk: 900, def: 700, rarity: "N" },
  { id: "vol2-bewitching-phantom-thief", name: "魅惑の怪盗", cardType: "monster", kind: "魔法使い族", attribute: "闇", level: 2, atk: 700, def: 700, rarity: "N" },
  { id: "vol2-larvas", name: "ラーバス", cardType: "monster", kind: "獣族", attribute: "地", level: 3, atk: 800, def: 1000, rarity: "N" },
  { id: "vol2-hard-armor", name: "ハードアーマー", cardType: "monster", kind: "戦士族", attribute: "地", level: 3, atk: 300, def: 1200, rarity: "N" },
  { id: "vol2-man-eater", name: "マンイーター", cardType: "monster", kind: "植物族", attribute: "地", level: 2, atk: 800, def: 600, rarity: "N" },
  { id: "vol2-m-w1", name: "マグネッツ１号", cardType: "monster", kind: "戦士族", attribute: "地", level: 3, atk: 1000, def: 500, rarity: "N" },
  { id: "vol2-m-w2", name: "マグネッツ２号", cardType: "monster", kind: "戦士族", attribute: "地", level: 3, atk: 500, def: 1000, rarity: "N" },
  { id: "vol2-spirit-harp", name: "ハープの精", cardType: "monster", kind: "天使族", attribute: "光", level: 4, atk: 800, def: 2000, rarity: "N" },
  { id: "vol2-armail", name: "アーメイル", cardType: "monster", kind: "戦士族", attribute: "地", level: 3, atk: 700, def: 1300, rarity: "N" },
  { id: "vol2-killer-claw", name: "キラー・ザ・クロー", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 3, atk: 1000, def: 800, rarity: "N" },
  { id: "vol2-terra-terrible", name: "魔人 テラ", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 4, atk: 1200, def: 1300, rarity: "N" },
  { id: "vol2-drover", name: "ドローバ", cardType: "monster", kind: "水族", attribute: "水", level: 3, atk: 900, def: 800, rarity: "N" },
  { id: "vol2-solitude", name: "ソリテュード", cardType: "monster", kind: "獣戦士族", attribute: "地", level: 3, atk: 1050, def: 1000, rarity: "N" },
  { id: "vol2-spider-man", name: "蜘蛛男", cardType: "monster", kind: "昆虫族", attribute: "地", level: 3, atk: 700, def: 1400, rarity: "N" },
  { id: "vol2-wood-remains", name: "森の屍", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 3, atk: 1000, def: 900, rarity: "N" },
  { id: "vol2-d-napoleon", name: "D・ナポレオン", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 2, atk: 800, def: 400, rarity: "N" },
  { id: "vol2-enchanting-mermaid", name: "恍惚の人魚", cardType: "monster", kind: "魚族", attribute: "水", level: 3, atk: 1200, def: 900, rarity: "N" },
  { id: "vol2-stone-armadiller", name: "ストーン・アルマジラー", cardType: "monster", kind: "岩石族", attribute: "地", level: 3, atk: 800, def: 1200, rarity: "N" },
  { id: "vol2-mavelus", name: "マブラス", cardType: "monster", kind: "鳥獣族", attribute: "風", level: 4, atk: 1300, def: 900, rarity: "N", fusion: true },
  { id: "vol2-holograh", name: "ホログラー", cardType: "monster", kind: "機械族", attribute: "地", level: 3, atk: 1100, def: 700, rarity: "N" },
  { id: "vol2-dragoness-wicked-knight", name: "魔装騎士ドラゴネス", cardType: "monster", kind: "戦士族", attribute: "風", level: 3, atk: 1200, def: 900, rarity: "N", fusion: true },
  { id: "vol2-one-eyed-shield-dragon", name: "一眼の盾竜", cardType: "monster", kind: "ドラゴン族", attribute: "風", level: 3, atk: 700, def: 1300, rarity: "N" },
  { id: "vol2-dark-energy", name: "闇・エネルギー", cardType: "spell", kind: "装備魔法", rarity: "R" },
  { id: "vol2-laser-cannon-armor", name: "レーザー砲機甲鎧", cardType: "spell", kind: "装備魔法", rarity: "R" },
  { id: "vol2-vile-germs", name: "魔菌", cardType: "spell", kind: "装備魔法", rarity: "R" },
  { id: "vol2-machine-conversion-factory", name: "機械改造工場", cardType: "spell", kind: "装備魔法", rarity: "R" },
  { id: "vol2-raise-body-heat", name: "体温の上昇", cardType: "spell", kind: "装備魔法", rarity: "R" },
  { id: "vol2-goblin-secret-remedy", name: "ゴブリンの秘薬", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "vol2-final-flame", name: "火あぶりの刑", cardType: "spell", kind: "通常魔法", rarity: "SR" },
  { id: "vol2-swords-revealing-light", name: "光の護封剣", cardType: "spell", kind: "通常魔法", rarity: "UR" },
  { id: "vol2-monster-reborn", name: "死者蘇生", cardType: "spell", kind: "通常魔法", rarity: "SR" },
  { id: "vol2-de-spell", name: "魔法除去", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "vol3-left-leg", name: "封印されし者の左足", cardType: "monster", kind: "魔法使い族", attribute: "闇", level: 1, atk: 200, def: 300, rarity: "UR" },
  { id: "vol3-beaver-warrior", name: "ルイーズ", cardType: "monster", kind: "獣戦士族", attribute: "地", level: 4, atk: 1200, def: 1500, rarity: "N" },
  { id: "vol3-gaia-dragon-champion", name: "竜騎士ガイア", cardType: "monster", kind: "ドラゴン族", attribute: "風", level: 7, atk: 2600, def: 2100, rarity: "SE", fusion: true },
  { id: "vol3-rogue-doll", name: "ホーリー・ドール", cardType: "monster", kind: "魔法使い族", attribute: "光", level: 4, atk: 1600, def: 1000, rarity: "R" },
  { id: "vol3-giant-soldier-stone", name: "岩石の巨兵", cardType: "monster", kind: "岩石族", attribute: "地", level: 3, atk: 1300, def: 2000, rarity: "N" },
  { id: "vol3-red-eyes", name: "真紅眼の黒竜", cardType: "monster", kind: "ドラゴン族", attribute: "闇", level: 7, atk: 2400, def: 2000, rarity: "UR" },
  { id: "vol3-reaper-cards", name: "カードを狩る死神", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 5, atk: 1380, def: 1930, rarity: "N", effect: true },
  { id: "vol3-barox", name: "バロックス", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 5, atk: 1380, def: 1530, rarity: "N", fusion: true },
  { id: "vol3-sleeping-lion", name: "眠れる獅子", cardType: "monster", kind: "獣族", attribute: "地", level: 4, atk: 700, def: 1700, rarity: "N" },
  { id: "vol3-ansatsu", name: "アサシン", cardType: "monster", kind: "戦士族", attribute: "地", level: 5, atk: 1700, def: 1200, rarity: "R" },
  { id: "vol3-witty-phantom", name: "魔人デスサタン", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 4, atk: 1400, def: 1300, rarity: "N" },
  { id: "vol3-akihiron", name: "カクタス", cardType: "monster", kind: "水族", attribute: "水", level: 5, atk: 1700, def: 1400, rarity: "R" },
  { id: "vol3-frenzied-panda", name: "キラーパンダ", cardType: "monster", kind: "獣族", attribute: "地", level: 4, atk: 1200, def: 1000, rarity: "N" },
  { id: "vol3-mabarrel", name: "マキャノン", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 5, atk: 1700, def: 1400, rarity: "R" },
  { id: "vol3-skull-stalker", name: "デス・ストーカー", cardType: "monster", kind: "戦士族", attribute: "闇", level: 3, atk: 900, def: 800, rarity: "N" },
  { id: "vol3-rare-fish", name: "レア・フィッシュ", cardType: "monster", kind: "魚族", attribute: "水", level: 4, atk: 1500, def: 1200, rarity: "N", fusion: true },
  { id: "vol3-fireyarou", name: "炎の魔神", cardType: "monster", kind: "炎族", attribute: "炎", level: 4, atk: 1300, def: 1000, rarity: "N" },
  { id: "vol3-giant-mech-soldier", name: "機械の巨兵", cardType: "monster", kind: "機械族", attribute: "地", level: 6, atk: 1750, def: 1900, rarity: "R" },
  { id: "vol3-metal-dragon", name: "メタル・ドラゴン", cardType: "monster", kind: "機械族", attribute: "風", level: 6, atk: 1850, def: 1700, rarity: "N", fusion: true },
  { id: "vol3-spike-seadra", name: "スパイクシードラ", cardType: "monster", kind: "海竜族", attribute: "水", level: 5, atk: 1600, def: 1300, rarity: "N" },
  { id: "vol3-tripwire-beast", name: "地雷獣", cardType: "monster", kind: "雷族", attribute: "地", level: 4, atk: 1200, def: 1300, rarity: "N" },
  { id: "vol3-skull-red-bird", name: "スカイ・ハンター", cardType: "monster", kind: "鳥獣族", attribute: "風", level: 4, atk: 1550, def: 1200, rarity: "N" },
  { id: "vol3-armed-ninja", name: "青い忍者", cardType: "monster", kind: "戦士族", attribute: "地", level: 1, atk: 300, def: 300, rarity: "N", effect: true },
  { id: "vol3-ganigumo", name: "ガニグモ", cardType: "monster", kind: "昆虫族", attribute: "地", level: 2, atk: 600, def: 800, rarity: "N" },
  { id: "vol3-flower-wolf", name: "フラワー・ウルフ", cardType: "monster", kind: "獣族", attribute: "地", level: 5, atk: 1800, def: 1400, rarity: "N", fusion: true },
  { id: "vol3-man-eater-bug", name: "人喰い虫", cardType: "monster", kind: "昆虫族", attribute: "地", level: 2, atk: 450, def: 600, rarity: "SR", effect: true },
  { id: "vol3-sand-stone", name: "サンド・ストーン", cardType: "monster", kind: "岩石族", attribute: "地", level: 5, atk: 1300, def: 1600, rarity: "N" },
  { id: "vol3-eldeen", name: "エルディーン", cardType: "monster", kind: "魔法使い族", attribute: "光", level: 3, atk: 950, def: 1000, rarity: "N" },
  { id: "vol3-kamakiriman", name: "カマキラー", cardType: "monster", kind: "昆虫族", attribute: "地", level: 4, atk: 1150, def: 1400, rarity: "N" },
  { id: "vol3-skelengel", name: "スケルエンジェル", cardType: "monster", kind: "天使族", attribute: "光", level: 2, atk: 900, def: 400, rarity: "N", effect: true },
  { id: "vol3-hane-hane", name: "ハネハネ", cardType: "monster", kind: "獣族", attribute: "地", level: 2, atk: 450, def: 500, rarity: "SR", effect: true },
  { id: "vol3-misairuzame", name: "ナイル", cardType: "monster", kind: "魚族", attribute: "水", level: 5, atk: 1400, def: 1600, rarity: "N" },
  { id: "vol3-wandering-doomed", name: "さまよえる亡者", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 2, atk: 800, def: 600, rarity: "N" },
  { id: "vol3-steel-ogre-grotto", name: "鋼鉄の巨神像", cardType: "monster", kind: "機械族", attribute: "地", level: 5, atk: 1400, def: 1800, rarity: "N" },
  { id: "vol3-lesser-dragon", name: "レッサー・ドラゴン", cardType: "monster", kind: "ドラゴン族", attribute: "風", level: 4, atk: 1200, def: 1000, rarity: "N" },
  { id: "vol3-wretched-ghost", name: "屋根裏の物の怪", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 2, atk: 550, def: 400, rarity: "N" },
  { id: "vol3-darkworld-thorns", name: "魔界のイバラ", cardType: "monster", kind: "植物族", attribute: "地", level: 3, atk: 1200, def: 900, rarity: "N" },
  { id: "vol3-anthrosaurus", name: "恐竜人", cardType: "monster", kind: "恐竜族", attribute: "地", level: 3, atk: 1000, def: 850, rarity: "N" },
  { id: "vol3-drooling-lizard", name: "生き血をすするもの", cardType: "monster", kind: "爬虫類族", attribute: "地", level: 3, atk: 900, def: 800, rarity: "N" },
  { id: "vol3-binding-chain", name: "封印の鎖", cardType: "monster", kind: "天使族", attribute: "光", level: 3, atk: 1000, def: 1100, rarity: "N" },
  { id: "vol3-armored-starfish", name: "アーマード・スターフィッシュ", cardType: "monster", kind: "水族", attribute: "水", level: 4, atk: 850, def: 1400, rarity: "N" },
  { id: "vol3-succubus-knight", name: "サキュバス・ナイト", cardType: "monster", kind: "戦士族", attribute: "闇", level: 5, atk: 1650, def: 1300, rarity: "N" },
  { id: "vol3-silver-bow-arrow", name: "銀の弓矢", cardType: "spell", kind: "装備魔法", rarity: "N" },
  { id: "vol3-dragon-treasure", name: "ドラゴンの秘宝", cardType: "spell", kind: "装備魔法", rarity: "N" },
  { id: "vol3-electro-whip", name: "電撃鞭", cardType: "spell", kind: "装備魔法", rarity: "N" },
  { id: "vol3-mystical-moon", name: "魔性の月", cardType: "spell", kind: "装備魔法", rarity: "N" },
  { id: "vol3-stop-defense", name: "『守備』封じ", cardType: "spell", kind: "通常魔法", rarity: "SR" },
  { id: "vol3-follow-wind", name: "フォロー・ウィンド", cardType: "spell", kind: "装備魔法", rarity: "N" },
  { id: "vol3-pot-of-greed", name: "強欲な壺", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "vol3-gravedigger-ghoul", name: "墓掘りグール", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "vol4-armor-lizard", name: "鎧蜥蜴", cardType: "monster", kind: "爬虫類族", attribute: "地", level: 4, atk: 1500, def: 1200, rarity: "N" },
  { id: "vol4-absolver", name: "アブソリューター", cardType: "monster", kind: "鳥獣族", attribute: "風", level: 4, atk: 1300, def: 1400, rarity: "N" },
  { id: "vol4-water-girl", name: "ウォーター・ガール", cardType: "monster", kind: "水族", attribute: "水", level: 4, atk: 1250, def: 1000, rarity: "N" },
  { id: "vol4-ancient-elf", name: "エンシェント・エルフ", cardType: "monster", kind: "魔法使い族", attribute: "光", level: 4, atk: 1450, def: 1200, rarity: "N" },
  { id: "vol4-tao", name: "陰陽師 タオ", cardType: "monster", kind: "魔法使い族", attribute: "地", level: 3, atk: 1200, def: 900, rarity: "N" },
  { id: "vol4-ogre-rock", name: "岩窟魔人オーガ・ロック", cardType: "monster", kind: "岩石族", attribute: "地", level: 3, atk: 800, def: 1200, rarity: "N" },
  { id: "vol4-caterpillar", name: "青虫", cardType: "monster", kind: "昆虫族", attribute: "地", level: 1, atk: 250, def: 300, rarity: "N" },
  { id: "vol4-cats-fairy", name: "キャッツ・フェアリー", cardType: "monster", kind: "獣族", attribute: "地", level: 3, atk: 1100, def: 900, rarity: "N" },
  { id: "vol4-grade-bill", name: "グレード・ビル", cardType: "monster", kind: "獣族", attribute: "地", level: 4, atk: 1250, def: 1300, rarity: "N" },
  { id: "vol4-black-shadow-ogre", name: "黒い影の鬼王", cardType: "monster", kind: "獣戦士族", attribute: "地", level: 4, atk: 1200, def: 1400, rarity: "N" },
  { id: "vol4-ancient-lizard-warrior", name: "古代のトカゲ戦士", cardType: "monster", kind: "爬虫類族", attribute: "地", level: 4, atk: 1400, def: 1100, rarity: "N" },
  { id: "vol4-dokuroizo", name: "死神のドクロイゾ", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 3, atk: 900, def: 1200, rarity: "N" },
  { id: "vol4-tongyo", name: "舌魚", cardType: "monster", kind: "魚族", attribute: "水", level: 4, atk: 1350, def: 800, rarity: "N" },
  { id: "vol4-trakadon", name: "トラコドン", cardType: "monster", kind: "恐竜族", attribute: "地", level: 3, atk: 1300, def: 800, rarity: "N" },
  { id: "vol4-dragon-human", name: "ドラゴヒューマン", cardType: "monster", kind: "戦士族", attribute: "地", level: 4, atk: 1300, def: 1100, rarity: "N" },
  { id: "vol4-winged-dragon-fortress", name: "砦を守る翼竜", cardType: "monster", kind: "ドラゴン族", attribute: "風", level: 4, atk: 1400, def: 1200, rarity: "N" },
  { id: "vol4-harpie-lady", name: "ハーピィ・レディ", cardType: "monster", kind: "鳥獣族", attribute: "風", level: 4, atk: 1300, def: 1400, rarity: "N" },
  { id: "vol4-destroyer-golem", name: "破壊のゴーレム", cardType: "monster", kind: "岩石族", attribute: "地", level: 4, atk: 1500, def: 1000, rarity: "N" },
  { id: "vol4-right-leg", name: "封印されし者の右足", cardType: "monster", kind: "魔法使い族", attribute: "闇", level: 1, atk: 200, def: 300, rarity: "UR" },
  { id: "vol4-petit-moth", name: "プチモス", cardType: "monster", kind: "昆虫族", attribute: "地", level: 1, atk: 300, def: 200, rarity: "N" },
  { id: "vol4-flame-viper", name: "フレイム・ヴァイパー", cardType: "monster", kind: "炎族", attribute: "地", level: 2, atk: 400, def: 450, rarity: "N" },
  { id: "vol4-magnum-lily", name: "マグナム・リリィ", cardType: "monster", kind: "植物族", attribute: "地", level: 3, atk: 1100, def: 600, rarity: "N" },
  { id: "vol4-monster-hunter", name: "魔物の狩人", cardType: "monster", kind: "戦士族", attribute: "地", level: 4, atk: 1500, def: 1200, rarity: "N" },
  { id: "vol4-water-dancer", name: "水の踊り子", cardType: "monster", kind: "水族", attribute: "水", level: 4, atk: 1400, def: 1200, rarity: "N" },
  { id: "vol4-mega-thunderball", name: "メガ・サンダーボール", cardType: "monster", kind: "雷族", attribute: "風", level: 2, atk: 750, def: 600, rarity: "N" },
  { id: "vol4-dark-assassin", name: "闇の暗殺者", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 4, atk: 1200, def: 1200, rarity: "N" },
  { id: "vol4-ground-bagroth", name: "陸戦型 バグロス", cardType: "monster", kind: "機械族", attribute: "地", level: 4, atk: 1500, def: 1000, rarity: "N" },
  { id: "vol4-angel-ears", name: "エンゼル・イヤーズ", cardType: "monster", kind: "天使族", attribute: "光", level: 5, atk: 1550, def: 1650, rarity: "N" },
  { id: "vol4-doma", name: "死の沈黙の天使 ドマ", cardType: "monster", kind: "天使族", attribute: "闇", level: 5, atk: 1600, def: 1400, rarity: "N" },
  { id: "vol4-god-fish", name: "神魚", cardType: "monster", kind: "魚族", attribute: "水", level: 5, atk: 1650, def: 1700, rarity: "N" },
  { id: "vol4-crawling-dragon", name: "地を這うドラゴン", cardType: "monster", kind: "ドラゴン族", attribute: "地", level: 5, atk: 1600, def: 1400, rarity: "N" },
  { id: "vol4-summoned-skull", name: "デーモンの召喚", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 6, atk: 2500, def: 1200, rarity: "UR" },
  { id: "vol4-trent", name: "トレント", cardType: "monster", kind: "植物族", attribute: "地", level: 5, atk: 1500, def: 1800, rarity: "N" },
  { id: "vol4-hunter-spider", name: "ハンター・スパイダー", cardType: "monster", kind: "昆虫族", attribute: "地", level: 5, atk: 1600, def: 1400, rarity: "N" },
  { id: "vol4-morinphen", name: "モリンフェン", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 5, atk: 1550, def: 1300, rarity: "N" },
  { id: "vol4-cocoon-evolution", name: "進化の繭", cardType: "monster", kind: "昆虫族", attribute: "地", level: 3, atk: 0, def: 2000, rarity: "SR", effect: true },
  { id: "vol4-magician-faith", name: "聖なる魔術師", cardType: "monster", kind: "魔法使い族", attribute: "光", level: 1, atk: 300, def: 400, rarity: "SR", effect: true },
  { id: "vol4-iron-scorpion", name: "鉄のサソリ", cardType: "monster", kind: "機械族", attribute: "地", level: 1, atk: 250, def: 300, rarity: "N", effect: true },
  { id: "vol4-electric-lizard", name: "でんきトカゲ", cardType: "monster", kind: "雷族", attribute: "地", level: 3, atk: 850, def: 800, rarity: "N", effect: true },
  { id: "vol4-mask-darkness", name: "闇の仮面", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 2, atk: 900, def: 400, rarity: "SR", effect: true },
  { id: "vol4-harpie-sisters", name: "ハーピィ・レディ三姉妹", cardType: "monster", kind: "鳥獣族", attribute: "風", level: 6, atk: 1950, def: 2100, rarity: "SE", effect: true },
  { id: "vol4-deepsea-shark", name: "深海に潜むサメ", cardType: "monster", kind: "魚族", attribute: "水", level: 5, atk: 1900, def: 1600, rarity: "N", fusion: true },
  { id: "vol4-pragtical", name: "プラグティカル", cardType: "monster", kind: "恐竜族", attribute: "地", level: 5, atk: 1900, def: 1500, rarity: "N", fusion: true },
  { id: "vol4-thunder-god-anger", name: "雷神の怒り", cardType: "monster", kind: "雷族", attribute: "風", level: 5, atk: 1900, def: 1400, rarity: "N", fusion: true },
  { id: "vol4-eternal-drought", name: "永遠の渇水", cardType: "spell", kind: "通常魔法", rarity: "R" },
  { id: "vol4-breath-god", name: "神の息吹", cardType: "spell", kind: "通常魔法", rarity: "R" },
  { id: "vol4-acid-storm", name: "酸の嵐", cardType: "spell", kind: "通常魔法", rarity: "R" },
  { id: "vol4-warrior-elimination", name: "戦士抹殺", cardType: "spell", kind: "通常魔法", rarity: "R" },
  { id: "vol4-insecticide", name: "トゲトゲ神の殺虫剤", cardType: "spell", kind: "通常魔法", rarity: "R" },
  { id: "vol4-elegant-egotist", name: "万華鏡－華麗なる分身－", cardType: "spell", kind: "通常魔法", rarity: "UR" },
];

export const packs: Pack[] = [
  {
    id: "vol-1",
    name: "Vol.1",
    releaseDate: "1999-02-04",
    category: "official",
    cardIds: cards.filter((card) => card.id.startsWith("vol1-")).map((card) => card.id),
  },
  {
    id: "vol-2",
    name: "Vol.2",
    releaseDate: "1999-03-27",
    category: "official",
    cardIds: cards.filter((card) => card.id.startsWith("vol2-")).map((card) => card.id),
  },
  {
    id: "vol-3",
    name: "Vol.3",
    releaseDate: "1999-05-27",
    category: "official",
    cardIds: cards.filter((card) => card.id.startsWith("vol3-")).map((card) => card.id),
  },
  {
    id: "vol-4",
    name: "Vol.4",
    releaseDate: "1999-07-22",
    category: "official",
    cardIds: cards.filter((card) => card.id.startsWith("vol4-")).map((card) => card.id),
  },
];

export const cardById = new Map(cards.map((card) => [card.id, card]));
