import { cardById, type Card, type Rarity } from "./card-data";
import { fusionRecipe } from "./fusion-rules.mjs";

export const rarityNames: Record<Rarity, string> = {
  SE: "シークレットレア",
  UR: "ウルトラレア",
  SR: "スーパーレア",
  R: "レア",
  N: "ノーマル",
};

const descriptions: Record<string, string> = {
  "vol1-legendary-sword": "戦士族モンスター1体のATK・DEFを300アップする。",
  "vol1-beast-fangs": "獣族モンスター1体のATK・DEFを300アップする。",
  "vol1-violet-crystal": "アンデット族モンスター1体のATK・DEFを300アップする。",
  "vol1-book-secret-arts": "魔法使い族モンスター1体のATK・DEFを300アップする。",
  "vol1-power-kaishin": "水族モンスター1体のATK・DEFを300アップする。",
  "vol1-dark-hole": "フィールドのモンスターをすべて破壊する。",
  "vol1-red-medicine": "自分のLPを500回復する。",
  "vol1-sparks": "相手に200ダメージを与える。",
  "vol1-fissure": "相手フィールドの最もATKが低い表側モンスター1体を破壊する。",
  "vol1-trap-hole": "相手がATK1000以上のモンスターを召喚した時、そのモンスターを破壊する。",
  "vol2-dark-energy": "悪魔族モンスター1体のATK・DEFを300アップする。",
  "vol2-laser-cannon-armor": "昆虫族モンスター1体のATK・DEFを300アップする。",
  "vol2-vile-germs": "植物族モンスター1体のATK・DEFを300アップする。",
  "vol2-machine-conversion-factory": "機械族モンスター1体のATK・DEFを300アップする。",
  "vol2-raise-body-heat": "恐竜族モンスター1体のATK・DEFを300アップする。",
  "vol2-goblin-secret-remedy": "自分のLPを600回復する。",
  "vol2-final-flame": "相手に600ダメージを与える。",
  "vol2-swords-revealing-light": "相手モンスターを表側にし、相手の攻撃を3ターン封じる。",
  "vol2-monster-reborn": "自分または相手の墓地からモンスター1体を特殊召喚する。",
  "vol2-de-spell": "フィールドのカード1枚を確認し、魔法カードなら破壊する。",
  "vol3-reaper-cards": "リバース：フィールドの罠カード1枚を確認し、罠カードなら破壊する。",
  "vol3-armed-ninja": "リバース：フィールドの魔法カード1枚を確認し、魔法カードなら破壊する。",
  "vol3-man-eater-bug": "リバース：フィールドのモンスター1体を破壊する。",
  "vol3-skelengel": "リバース：デッキからカードを1枚ドローする。",
  "vol3-hane-hane": "リバース：フィールドのモンスター1体を持ち主の手札に戻す。",
  "vol3-silver-bow-arrow": "天使族モンスター1体のATK・DEFを300アップする。",
  "vol3-dragon-treasure": "ドラゴン族モンスター1体のATK・DEFを300アップする。",
  "vol3-electro-whip": "雷族モンスター1体のATK・DEFを300アップする。",
  "vol3-mystical-moon": "獣戦士族モンスター1体のATK・DEFを300アップする。",
  "vol3-stop-defense": "相手の守備表示モンスター1体を攻撃表示に変更する。",
  "vol3-follow-wind": "鳥獣族モンスター1体のATK・DEFを300アップする。",
  "vol3-pot-of-greed": "デッキからカードを2枚ドローする。",
  "vol3-gravedigger-ghoul": "相手の墓地からモンスターを2体まで除外する。",
  "vol4-cocoon-evolution": "手札から表側表示のプチモスに装備できる。装備中はATK0・DEF2000になる。",
  "vol4-magician-faith": "リバース：自分の墓地から魔法カード1枚を手札に戻す。",
  "vol4-iron-scorpion": "機械族以外がこのカードを攻撃した場合、その攻撃側の3ターン目のエンドフェイズに破壊する。",
  "vol4-electric-lizard": "このカードを攻撃したアンデット族以外のモンスターは、次のターン攻撃できない。",
  "vol4-mask-darkness": "リバース：自分の墓地から罠カード1枚を手札に戻す。",
  "vol4-harpie-sisters": "通常召喚できない。万華鏡－華麗なる分身－の効果で特殊召喚する。",
  "vol4-eternal-drought": "フィールドの表側表示の水族モンスターをすべて破壊する。",
  "vol4-breath-god": "フィールドの表側表示の岩石族モンスターをすべて破壊する。",
  "vol4-acid-storm": "フィールドの表側表示の機械族モンスターをすべて破壊する。",
  "vol4-warrior-elimination": "フィールドの表側表示の戦士族モンスターをすべて破壊する。",
  "vol4-insecticide": "フィールドの表側表示の昆虫族モンスターをすべて破壊する。",
  "vol4-elegant-egotist": "ハーピィ・レディがいる時、手札・デッキからハーピィ1体を特殊召喚する。",
  "vol5-larvae-moth": "進化の繭を装備したプチモスを、装備から数えて2回目の自分ターン以降に生け贄にして特殊召喚する。",
  "vol5-white-magical-hat": "相手に戦闘ダメージを与えた時、相手の手札をランダムに1枚捨てる。",
  "vol5-big-eye": "リバース：自分のデッキの上から5枚を確認し、好きな順番でデッキの上に戻す。",
  "vol5-masked-sorcerer": "相手に戦闘ダメージを与えた時、デッキからカードを1枚ドローする。",
  "vol5-sanga": "相手ターンに攻撃された時、攻撃モンスターのATKをダメージ計算時のみ0にできる。この効果は表側表示で1度だけ使える。",
  "vol5-kazejin": "相手ターンに攻撃された時、攻撃モンスターのATKをダメージ計算時のみ0にできる。この効果は表側表示で1度だけ使える。",
  "vol5-suijin": "相手ターンに攻撃された時、攻撃モンスターのATKをダメージ計算時のみ0にできる。この効果は表側表示で1度だけ使える。",
  "vol5-mystic-lamp": "相手に直接攻撃できる。",
  "vol5-leghul": "相手に直接攻撃できる。",
  "vol5-ooguchi": "相手に直接攻撃できる。",
  "vol5-blast-juggler": "自分のスタンバイフェイズにこのカードを生け贄にし、ATK1000以下の表側モンスター2体を破壊できる。",
  "vol5-jinzo-7": "相手に直接攻撃できる。",
  "vol5-rainbow-flower": "相手に直接攻撃できる。",
  "vol5-queens-double": "相手に直接攻撃できる。",
  "vol5-tribute-doomed": "手札を1枚捨て、フィールドのモンスター1体を破壊する。",
  "vol5-soul-release": "自分または相手の墓地からカードを合計5枚まで除外する。",
  "vol5-cheerful-coffin": "手札からモンスターカードを3枚まで墓地へ捨てる。",
  "vol5-change-heart": "相手モンスター1体のコントロールをエンドフェイズまで得る。",
  "vol5-fake-trap": "自分の罠カードが破壊される時、このカードを代わりに破壊する。",
  "vol5-anti-raigeki": "相手がサンダー・ボルトを発動した時、その効果を無効にして相手モンスターをすべて破壊する。",
  "vol5-call-darkness": "このカードがある限り死者蘇生を使用できず、死者蘇生で特殊召喚されたモンスターを墓地へ送る。",
  "vol6-shadow-ghoul": "自分の墓地のモンスター1体につき、このカードのATKは100アップする。",
  "vol6-great-moth": "進化の繭を装備したプチモスを、装備から数えて4回目の自分ターン以降に生け贄にして特殊召喚する。",
  "vol6-sangan": "このカードがフィールドから墓地へ送られた時、デッキからATK1500以下のモンスター1体を手札に加える。",
  "vol6-witch-black-forest": "このカードがフィールドから墓地へ送られた時、デッキからDEF1500以下のモンスター1体を手札に加える。",
  "vol6-cannon-soldier": "自分フィールドのモンスター1体を生け贄にするたび、相手に500ダメージを与える。",
  "vol6-dragon-piper": "リバース：フィールドの「ドラゴン族・封印の壺」を破壊する。破壊した場合、表側のドラゴン族モンスターは全て攻撃表示になる。",
  "vol6-seven-tools": "罠カードが発動した時、1000LPを払って発動できる。その発動を無効にし破壊する。",
  "vol6-magic-jammer": "魔法カードが発動した時、手札を1枚捨てて発動できる。その発動を無効にし破壊する。",
  "vol6-horn-heaven": "自分か相手がモンスターを召喚・反転召喚・特殊召喚する際に、自分フィールドのモンスター1体を生け贄にして発動できる。それを無効にし、そのモンスターを破壊する。",
  "vol6-solemn-judgment": "LPを半分払って発動できる。魔法・罠カードの発動、またはモンスターの召喚・反転召喚・特殊召喚を無効にし破壊する。",
  "vol6-muka-muka": "このカードのATK・DEFは、自分の手札の枚数×300アップする。",
  "vol6-hoshiningen": "光属性モンスターのATKは500アップし、闇属性モンスターのATKは400ダウンする。",
  "vol6-star-boy": "水属性モンスターのATKは500アップし、炎属性モンスターのATKは400ダウンする。",
  "vol6-milus-radiant": "地属性モンスターのATKは500アップし、風属性モンスターのATKは400ダウンする。",
  "vol6-little-chimera": "炎属性モンスターのATKは500アップし、水属性モンスターのATKは400ダウンする。",
  "vol6-bladefly": "風属性モンスターのATKは500アップし、地属性モンスターのATKは400ダウンする。",
  "vol6-witch-apprentice": "闇属性モンスターのATKは500アップし、光属性モンスターのATKは400ダウンする。",
  "vol7-dimensional-warrior": "このカードがモンスターと戦闘を行った時、そのモンスターとこのカードをゲームから除外する。",
  "vol7-thunder-nyan-nyan": "リバース：3000LP回復する。このカードがフィールドから墓地へ送られた時、5000LPを失う。",
  "vol7-kuriboh": "相手ターンの戦闘ダメージ計算時に手札から捨て、その戦闘で受ける戦闘ダメージを0にする。",
  "vol7-dark-elf": "このカードは1000LPを払わなければ攻撃できない。",
  "vol7-sword-queen": "リバース：相手フィールドの魔法・罠カード1枚につき、相手に500ダメージを与える。",
  "vol7-unhappy-maiden": "このカードが戦闘で破壊され墓地へ送られた時、そのターンのバトルフェイズを終了する。",
  "vol7-matango": "自分のスタンバイフェイズ毎に300ダメージを受ける。自分のエンドフェイズに500LPを払えば、相手にコントロールを移す。",
  "vol7-catapult-turtle": "1ターンに1度、自分フィールドのモンスター1体を生け贄にし、そのATKの半分のダメージを相手に与える。",
  "vol7-thunder-dragon": "自分メインフェイズに手札から捨て、デッキから別のサンダー・ドラゴンを2枚まで手札に加える。",
  "vol7-barbarian-1": "自分フィールドの表側表示のバーバリアン2号1体につき、ATKが500アップする。",
  "vol7-barbarian-2": "自分フィールドの表側表示のバーバリアン1号1体につき、ATKが500アップする。",
  "vol7-barrel-dragon": "1ターンに1度、相手モンスター1体を選びコイントスを3回行う。2回以上が表なら、そのモンスターを破壊する。",
  "vol7-tremendous-fire": "相手に1000ダメージを与え、自分は500ダメージを受ける。",
  "vol7-stop-attack": "相手フィールドの表側攻撃表示モンスター1体を表側守備表示にする。",
  "vol7-germ-infection": "機械族以外に装備できる。装備モンスターのATKは自分のスタンバイフェイズ毎に300ダウンする。",
  "vol7-paralyzing-potion": "機械族以外に装備できる。装備モンスターは攻撃できない。",
  "vol7-sword-deep-seated": "装備モンスターのATK・DEFを500アップする。墓地へ送られた時、デッキの一番上に戻る。",
  "vol7-shield-sword": "発動時に存在する全ての表側表示モンスターの元々のATKとDEFを、エンドフェイズまで入れ替える。",
  "vol7-robbin-goblin": "自分のモンスターが相手に戦闘ダメージを与える度に、相手の手札をランダムに1枚捨てる。",
  "vol7-mirror-force": "相手モンスターの攻撃宣言時、相手フィールドの攻撃表示モンスターを全て破壊する。",
  "bo1-blue-potion": "自分のLPを400回復する。",
  "bo1-thunder": "相手に300ダメージを与える。",
  "bo2-dark-piercing-sword": "闇属性モンスターに装備できる。装備モンスターのATKを400アップし、DEFを200ダウンする。",
  "bo2-elf-light": "光属性モンスターに装備できる。装備モンスターのATKを400アップし、DEFを200ダウンする。",
  "bo2-steel-shell": "水属性モンスターに装備できる。装備モンスターのATKを400アップし、DEFを200ダウンする。",
  "bo2-awakening": "地属性モンスターに装備できる。装備モンスターのATKを400アップし、DEFを200ダウンする。",
  "bo2-angel-blood": "自分のLPを800回復する。",
  "bo2-fire": "相手に800ダメージを与える。",
  "bo2-light-reveal": "相手フィールドの裏側表示モンスターを全て表側表示にする。リバース効果は発動しない。",
  "bo2-burning-spear": "炎属性モンスターに装備できる。装備モンスターのATKを400アップし、DEFを200ダウンする。",
  "bo2-gust-fan": "風属性モンスターに装備できる。装備モンスターのATKを400アップし、DEFを200ダウンする。",
  "bo2-amateur-spy": "相手の手札を1枚選んで確認する。",
  "bo3-udan": "フィールド上の表側表示の植物族モンスター1体につき、ATKが100アップする。",
  "bo3-dark-artist": "光属性モンスターの攻撃を受けた時、このカードのDEFは半分になる。",
  "bo3-patrol-robo": "自分のスタンバイフェイズに、相手フィールドのセットされたカード1枚を確認できる。",
  "bo3-hourglass-courage": "表側表示になってから3ターンの間はATK・DEFが半分になり、4ターン目以降は倍になる。",
  "bo3-reverse-trap": "ターン終了まで、ATK・DEFをアップ・ダウンさせる効果を逆にする。",
  "bo3-reinforcements": "ターン終了まで、モンスター1体のATKを500アップする。",
  "bo3-castle-walls": "ターン終了まで、モンスター1体のDEFを500アップする。",
  "bo3-ultimate-offering": "500LPを払うことで、通常召喚に加えてモンスター1体を召喚できる。",
  "bo3-ancient-telescope": "相手のデッキの上から5枚を確認し、元の順番に戻す。",
  "bo4-worm-beast": "召喚したターンの終了時、このカードを持ち主の手札に戻す。",
  "bo4-zone-eater": "このカードの攻撃を受けたモンスターは、5ターン後に破壊される。",
  "bo4-foreign-swordsman": "このカードの攻撃を受けたモンスターは、5ターン後に破壊される。",
  "bo4-mechanical-spider": "このカードの攻撃を受けた闇属性モンスターを、ダメージ計算後に破壊する。",
  "bo4-cockroach-knight": "このカードが墓地へ送られた時、デッキの一番上に戻る。",
  "bo4-graceful-charity": "デッキからカードを3枚引き、その後手札からカードを2枚捨てる。",
  "bo4-white-hole": "相手がブラック・ホールを発動した時、自分のモンスターの破壊を防ぐ。",
  "bo4-call-grave": "相手が死者蘇生を発動した時、その効果を無効にする。",
  "stb-dragon-capture-jar": "フィールドのドラゴン族モンスターを守備表示にし、表示形式の変更を封じる。",
  "stb-forest": "昆虫・獣・植物・獣戦士族のATK・DEFを200アップする。",
  "stb-wasteland": "恐竜・アンデット・岩石族のATK・DEFを200アップする。",
  "stb-mountain": "ドラゴン・鳥獣・雷族のATK・DEFを200アップする。",
  "stb-sogen": "戦士・獣戦士族のATK・DEFを200アップする。",
  "stb-umi": "水・魚・海竜・雷族を強化し、機械・炎族を弱体化する。",
  "stb-yami": "魔法使い・悪魔族を強化し、天使族を弱体化する。",
  "stb-raigeki": "相手フィールドのモンスターをすべて破壊する。",
  "stb-moyan-curry": "自分のLPを200回復する。",
  "stb-fireball": "相手に500ダメージを与える。",
  "stb-polymerization": "融合素材モンスターを使い、融合モンスター1体を融合召喚する。",
  "vol6-polymerization": "自分の手札・フィールドのモンスターを融合素材とし、融合モンスター1体を融合召喚する。",
  "stb-remove-trap": "フィールドの表側表示の罠カード1枚を破壊する。",
  "stb-two-pronged-attack": "自分のモンスター2体を破壊し、相手のモンスター1体を破壊する。",
};

export function cardDescription(card: Card) {
  if (descriptions[card.id]) return descriptions[card.id];
  if (card.fusion) {
    const recipe = fusionRecipe(card.id);
    if (recipe) return `融合素材：${recipe.map((id) => cardById.get(id)?.name ?? id).join(" ＋ ")}`;
    return "融合素材を使って融合召喚するモンスター。";
  }
  if (card.effect) return "効果モンスター。詳細な効果処理は順次対応予定。";
  if (card.cardType === "spell") return "魔法カード。詳細な効果処理は順次対応予定。";
  if (card.cardType === "trap") return "罠カード。詳細な効果処理は順次対応予定。";
  return "通常モンスター。";
}
