import type { Card, Pack } from "./card-data";

// 2000年9月28日発売時の全52種類。
export const curseOfAnubisCards: Card[] = [
  { id: "ca-00", name: "人造人間－サイコ・ショッカー", cardType: "monster", kind: "機械族", attribute: "闇", level: 6, atk: 2400, def: 1500, rarity: "SE", effect: true },
  { id: "ca-01", name: "鉄腕ゴーレム", cardType: "monster", kind: "機械族", attribute: "地", level: 6, atk: 1900, def: 2200, rarity: "N" },
  { id: "ca-02", name: "三ツ首のギドー", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 4, atk: 1200, def: 1400, rarity: "N" },
  { id: "ca-03", name: "寄生虫パラサイド", cardType: "monster", kind: "昆虫族", attribute: "地", level: 2, atk: 500, def: 300, rarity: "UR", effect: true },
  { id: "ca-04", name: "７カード", cardType: "spell", kind: "装備魔法", rarity: "N" },
  { id: "ca-05", name: "光の封札剣", cardType: "trap", kind: "通常罠", rarity: "SR" },
  { id: "ca-06", name: "連鎖破壊", cardType: "trap", kind: "通常罠", rarity: "UR" },
  { id: "ca-07", name: "刻の封印", cardType: "trap", kind: "通常罠", rarity: "N" },
  { id: "ca-08", name: "墓荒らし", cardType: "trap", kind: "通常罠", rarity: "N" },
  { id: "ca-09", name: "ホーリー・エルフの祝福", cardType: "trap", kind: "通常罠", rarity: "N" },
  { id: "ca-10", name: "真実の眼", cardType: "trap", kind: "永続罠", rarity: "N" },
  { id: "ca-11", name: "砂塵の大竜巻", cardType: "trap", kind: "通常罠", rarity: "N" },
  { id: "ca-12", name: "リビングデッドの呼び声", cardType: "trap", kind: "永続罠", rarity: "N" },
  { id: "ca-13", name: "ソロモンの律法書", cardType: "trap", kind: "通常罠", rarity: "R" },
  { id: "ca-14", name: "地殻変動", cardType: "trap", kind: "通常罠", rarity: "N" },
  { id: "ca-15", name: "ホーリージャベリン", cardType: "trap", kind: "通常罠", rarity: "N" },
  { id: "ca-16", name: "銀幕の鏡壁", cardType: "trap", kind: "永続罠", rarity: "SR" },
  { id: "ca-17", name: "突風", cardType: "trap", kind: "通常罠", rarity: "N" },
  { id: "ca-18", name: "猛吹雪", cardType: "trap", kind: "通常罠", rarity: "N" },
  { id: "ca-19", name: "ガラスの鎧", cardType: "trap", kind: "通常罠", rarity: "N" },
  { id: "ca-20", name: "世界の平定", cardType: "trap", kind: "通常罠", rarity: "N" },
  { id: "ca-21", name: "魔法探査の石版", cardType: "trap", kind: "通常罠", rarity: "N" },
  { id: "ca-22", name: "金属探知器", cardType: "trap", kind: "通常罠", rarity: "N" },
  { id: "ca-23", name: "白衣の天使", cardType: "trap", kind: "通常罠", rarity: "N" },
  { id: "ca-24", name: "便乗", cardType: "trap", kind: "永続罠", rarity: "N" },
  { id: "ca-25", name: "強制接収", cardType: "trap", kind: "永続罠", rarity: "N" },
  { id: "ca-26", name: "ＤＮＡ改造手術", cardType: "trap", kind: "永続罠", rarity: "N" },
  { id: "ca-27", name: "一族の掟", cardType: "trap", kind: "永続罠", rarity: "N" },
  { id: "ca-28", name: "補充要員", cardType: "trap", kind: "通常罠", rarity: "N" },
  { id: "ca-29", name: "大騒動", cardType: "trap", kind: "通常罠", rarity: "N" },
  { id: "ca-30", name: "停戦協定", cardType: "trap", kind: "通常罠", rarity: "N" },
  { id: "ca-31", name: "聖なる輝き", cardType: "trap", kind: "永続罠", rarity: "N" },
  { id: "ca-32", name: "正々堂々", cardType: "trap", kind: "永続罠", rarity: "N" },
  { id: "ca-33", name: "王宮の勅命", cardType: "trap", kind: "永続罠", rarity: "SR" },
  { id: "ca-34", name: "マジカルシルクハット", cardType: "trap", kind: "通常罠", rarity: "SR" },
  { id: "ca-35", name: "抹殺の使徒", cardType: "spell", kind: "通常魔法", rarity: "R" },
  { id: "ca-36", name: "撲滅の使徒", cardType: "spell", kind: "通常魔法", rarity: "R" },
  { id: "ca-37", name: "浅すぎた墓穴", cardType: "spell", kind: "通常魔法", rarity: "R" },
  { id: "ca-38", name: "早すぎた埋葬", cardType: "spell", kind: "装備魔法", rarity: "R" },
  { id: "ca-39", name: "検閲", cardType: "spell", kind: "永続魔法", rarity: "N" },
  { id: "ca-40", name: "禁止令", cardType: "spell", kind: "永続魔法", rarity: "R" },
  { id: "ca-41", name: "カオスポッド", cardType: "monster", kind: "岩石族", attribute: "地", level: 3, atk: 800, def: 700, rarity: "N", effect: true },
  { id: "ca-42", name: "フレイムキラー", cardType: "monster", kind: "炎族", attribute: "炎", level: 5, atk: 1900, def: 1300, rarity: "N" },
  { id: "ca-43", name: "ビッグバンドラゴン", cardType: "monster", kind: "炎族", attribute: "炎", level: 6, atk: 2200, def: 1700, rarity: "N" },
  { id: "ca-44", name: "バーニングソルジャー", cardType: "monster", kind: "炎族", attribute: "炎", level: 4, atk: 1700, def: 1150, rarity: "N" },
  { id: "ca-45", name: "ミスターボルケーノ", cardType: "monster", kind: "炎族", attribute: "炎", level: 5, atk: 2100, def: 1300, rarity: "N" },
  { id: "ca-46", name: "炎の剣豪", cardType: "monster", kind: "炎族", attribute: "炎", level: 4, atk: 1700, def: 1100, rarity: "N" },
  { id: "ca-47", name: "精神寄生体", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 2, atk: 300, def: 800, rarity: "N", effect: true },
  { id: "ca-48", name: "メカファルコン", cardType: "monster", kind: "機械族", attribute: "風", level: 4, atk: 1400, def: 1200, rarity: "N" },
  { id: "ca-49", name: "フライングマンティス", cardType: "monster", kind: "昆虫族", attribute: "風", level: 4, atk: 1500, def: 800, rarity: "N" },
  { id: "ca-50", name: "バードマン", cardType: "monster", kind: "鳥獣族", attribute: "風", level: 4, atk: 1800, def: 600, rarity: "N" },
  { id: "ca-51", name: "バスター・ブレイダー", cardType: "monster", kind: "戦士族", attribute: "地", level: 7, atk: 2600, def: 2300, rarity: "UR", effect: true },
];

export const curseOfAnubisPack: Pack = {
  id: "curse-of-anubis",
  name: "Curse of Anubis －アヌビスの呪い－",
  releaseDate: "2000-09-28",
  category: "official",
  cardIds: curseOfAnubisCards.map((card) => card.id),
};

export const curseOfAnubisReadyCardIds = [
  "ca-00", "ca-01", "ca-02", "ca-06", "ca-09", "ca-30", "ca-42", "ca-43", "ca-44", "ca-45", "ca-46", "ca-48", "ca-49", "ca-50", "ca-51",
] as const;
