import type { Card, Pack } from "./card-data";

export const earlyProductCards: Card[] = [
  { id: "bo1-gargoyle", name: "ガーゴイル", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 3, atk: 1000, def: 500, rarity: "N" },
  { id: "bo1-elekids", name: "エレキッズ", cardType: "monster", kind: "雷族", attribute: "光", level: 3, atk: 1000, def: 500, rarity: "N" },
  { id: "bo1-man-eating-plant", name: "人喰い植物", cardType: "monster", kind: "植物族", attribute: "地", level: 2, atk: 800, def: 600, rarity: "N" },
  { id: "bo1-ultimater", name: "格闘戦士アルティメーター", cardType: "monster", kind: "戦士族", attribute: "地", level: 3, atk: 700, def: 1000, rarity: "N" },
  { id: "bo1-wicked-flame-wing", name: "邪炎の翼", cardType: "monster", kind: "炎族", attribute: "炎", level: 2, atk: 700, def: 600, rarity: "N" },
  { id: "bo1-beckoning-grave", name: "手招きする墓場", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 3, atk: 700, def: 900, rarity: "N" },
  { id: "bo1-nightmare-scorpion", name: "ナイトメア・スコーピオン", cardType: "monster", kind: "昆虫族", attribute: "地", level: 3, atk: 900, def: 800, rarity: "N" },
  { id: "bo1-yamatano-scroll", name: "ヤマタノ竜絵巻", cardType: "monster", kind: "ドラゴン族", attribute: "風", level: 2, atk: 900, def: 300, rarity: "N" },
  { id: "bo1-dark-plant", name: "ダーク・プラント", cardType: "monster", kind: "植物族", attribute: "闇", level: 1, atk: 300, def: 400, rarity: "N" },
  { id: "bo1-weather-control", name: "ウェザー・コントロール", cardType: "monster", kind: "天使族", attribute: "光", level: 2, atk: 600, def: 400, rarity: "N" },
  { id: "bo1-holy-chain", name: "聖なる鎖", cardType: "monster", kind: "天使族", attribute: "光", level: 2, atk: 700, def: 700, rarity: "N" },
  { id: "bo1-wind-guardian", name: "風の番人 ジン", cardType: "monster", kind: "魔法使い族", attribute: "風", level: 3, atk: 700, def: 900, rarity: "N" },
  { id: "bo1-shadow-who-controls-dark", name: "闇を司る影", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 3, atk: 800, def: 700, rarity: "N" },
  { id: "bo1-melting-red-shadow", name: "とろける赤き影", cardType: "monster", kind: "水族", attribute: "水", level: 2, atk: 500, def: 700, rarity: "N" },
  { id: "bo1-dig-beak", name: "ディッグ・ビーク", cardType: "monster", kind: "獣族", attribute: "地", level: 2, atk: 500, def: 800, rarity: "N" },
  { id: "bo1-ancient-jar", name: "太古の壺", cardType: "monster", kind: "岩石族", attribute: "地", level: 1, atk: 400, def: 200, rarity: "N" },
  { id: "bo1-hurricail", name: "ハリケル", cardType: "monster", kind: "魔法使い族", attribute: "風", level: 2, atk: 900, def: 200, rarity: "N" },
  { id: "bo1-fire-eye", name: "ファイヤー・アイ", cardType: "monster", kind: "炎族", attribute: "炎", level: 2, atk: 800, def: 600, rarity: "N" },
  { id: "bo1-saturn", name: "サターナ", cardType: "monster", kind: "魔法使い族", attribute: "闇", level: 2, atk: 700, def: 600, rarity: "N" },
  { id: "bo1-holy-power", name: "ホーリー・パワー", cardType: "monster", kind: "魔法使い族", attribute: "光", level: 2, atk: 600, def: 800, rarity: "N" },
  { id: "bo1-hellgate-dice", name: "ヘルゲート・ディーグ", cardType: "monster", kind: "獣族", attribute: "闇", level: 3, atk: 700, def: 800, rarity: "N" },
  { id: "bo1-phalanx", name: "ファランクス", cardType: "monster", kind: "獣族", attribute: "地", level: 3, atk: 800, def: 900, rarity: "N" },
  { id: "bo1-drone", name: "ドローン", cardType: "monster", kind: "戦士族", attribute: "地", level: 2, atk: 900, def: 500, rarity: "N" },
  { id: "bo1-zombie-lamp", name: "ゾンビランプ", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 2, atk: 500, def: 400, rarity: "N" },
  { id: "bo1-happy-lover", name: "ハッピー・ラヴァー", cardType: "monster", kind: "天使族", attribute: "光", level: 2, atk: 800, def: 500, rarity: "N" },
  { id: "bo1-ghost", name: "ゴースト", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 2, atk: 600, def: 800, rarity: "N" },
  { id: "bo1-gross", name: "グロス", cardType: "monster", kind: "水族", attribute: "水", level: 3, atk: 900, def: 700, rarity: "N" },
  { id: "bo1-spiked-snail", name: "スピック", cardType: "monster", kind: "鳥獣族", attribute: "風", level: 2, atk: 600, def: 500, rarity: "N" },
  { id: "bo1-midnight-fiend", name: "ミッドナイト・デビル", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 2, atk: 800, def: 600, rarity: "N" },
  { id: "bo1-vishwar-randi", name: "ヴィシュワ・ランディー", cardType: "monster", kind: "戦士族", attribute: "闇", level: 3, atk: 900, def: 700, rarity: "N" },
  { id: "bo1-water-element", name: "ウォーター・エレメント", cardType: "monster", kind: "水族", attribute: "水", level: 3, atk: 900, def: 700, rarity: "N" },
  { id: "bo1-embryonic-beast", name: "未熟な悪魔", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 2, atk: 500, def: 750, rarity: "N" },
  { id: "bo1-wicked-dragon-two-heads", name: "魔頭を持つ邪竜", cardType: "monster", kind: "ドラゴン族", attribute: "風", level: 3, atk: 900, def: 900, rarity: "N" },
  { id: "bo1-blue-potion", name: "ブルー・ポーション", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "bo1-thunder", name: "雷鳴", cardType: "spell", kind: "通常魔法", rarity: "N" },

  { id: "stb-blue-eyes", name: "青眼の白龍", cardType: "monster", kind: "ドラゴン族", attribute: "光", level: 8, atk: 3000, def: 2500, rarity: "UR" },
  { id: "stb-hellbound", name: "ヘルバウンド", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 1, atk: 500, def: 200, rarity: "N" },
  { id: "stb-flame-swordsman", name: "炎の剣士", cardType: "monster", kind: "戦士族", attribute: "炎", level: 5, atk: 1800, def: 1600, rarity: "UR", fusion: true },
  { id: "stb-skull-servant", name: "ワイト", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 1, atk: 300, def: 200, rarity: "N" },
  { id: "stb-mountain-warrior", name: "マウンテン・ウォーリアー", cardType: "monster", kind: "獣戦士族", attribute: "地", level: 3, atk: 600, def: 1000, rarity: "N" },
  { id: "stb-basic-insect", name: "昆虫人間", cardType: "monster", kind: "昆虫族", attribute: "地", level: 2, atk: 500, def: 700, rarity: "N" },
  { id: "stb-shadow-fighter", name: "シャドウ・ファイター", cardType: "monster", kind: "戦士族", attribute: "闇", level: 2, atk: 800, def: 600, rarity: "N" },
  { id: "stb-flame-knight-killer", name: "炎の騎士 キラー", cardType: "monster", kind: "炎族", attribute: "炎", level: 3, atk: 1100, def: 800, rarity: "N", fusion: true },
  { id: "stb-mysterious-hand", name: "なぞの手", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 2, atk: 500, def: 500, rarity: "N" },
  { id: "stb-fiends-hand", name: "デビルツムリ", cardType: "monster", kind: "昆虫族", attribute: "闇", level: 3, atk: 700, def: 1300, rarity: "N" },
  { id: "stb-flame-manipulator", name: "炎を操る者", cardType: "monster", kind: "魔法使い族", attribute: "炎", level: 3, atk: 900, def: 1000, rarity: "N" },
  { id: "stb-necrolancer", name: "時の魔人 ネクロランサ", cardType: "monster", kind: "魔法使い族", attribute: "闇", level: 3, atk: 800, def: 900, rarity: "N" },
  { id: "stb-monster-egg", name: "モンスター・エッグ", cardType: "monster", kind: "戦士族", attribute: "地", level: 3, atk: 600, def: 900, rarity: "N" },
  { id: "stb-darkfire-dragon", name: "暗黒火炎龍", cardType: "monster", kind: "ドラゴン族", attribute: "闇", level: 4, atk: 1500, def: 1250, rarity: "N", fusion: true },
  { id: "stb-dark-prisoner", name: "ダーク・プリズナー", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 3, atk: 600, def: 1000, rarity: "N" },
  { id: "stb-monsturtle", name: "モンスタートル", cardType: "monster", kind: "水族", attribute: "水", level: 3, atk: 800, def: 1000, rarity: "N" },
  { id: "stb-masked-clown", name: "仮面道化", cardType: "monster", kind: "戦士族", attribute: "闇", level: 2, atk: 500, def: 700, rarity: "N" },
  { id: "stb-juggler", name: "ジャグラー", cardType: "monster", kind: "魔法使い族", attribute: "光", level: 3, atk: 600, def: 900, rarity: "N" },
  { id: "stb-mirage", name: "ミラージュ", cardType: "monster", kind: "鳥獣族", attribute: "光", level: 4, atk: 1100, def: 1400, rarity: "N" },
  { id: "stb-fusionist", name: "フュージョニスト", cardType: "monster", kind: "獣族", attribute: "地", level: 3, atk: 900, def: 700, rarity: "N", fusion: true },
  { id: "stb-key-mace", name: "キーメイス", cardType: "monster", kind: "天使族", attribute: "光", level: 1, atk: 400, def: 300, rarity: "N" },
  { id: "stb-sting", name: "スティング", cardType: "monster", kind: "炎族", attribute: "炎", level: 2, atk: 600, def: 500, rarity: "N" },
  { id: "stb-flame-ghost", name: "フレイム・ゴースト", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 3, atk: 1000, def: 800, rarity: "N", fusion: true },
  { id: "stb-two-mouth-darkruler", name: "二つの口を持つ闇の支配者", cardType: "monster", kind: "恐竜族", attribute: "地", level: 3, atk: 900, def: 700, rarity: "N" },
  { id: "stb-fiend-reflection", name: "魔人銃", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 2, atk: 600, def: 800, rarity: "N" },
  { id: "stb-magman", name: "マグマン", cardType: "monster", kind: "岩石族", attribute: "地", level: 3, atk: 900, def: 1000, rarity: "N" },
  { id: "stb-root-water", name: "ルート・ウォーター", cardType: "monster", kind: "魚族", attribute: "水", level: 3, atk: 900, def: 800, rarity: "N" },
  { id: "stb-moon-goddess", name: "月の女神 エルザェム", cardType: "monster", kind: "天使族", attribute: "光", level: 3, atk: 750, def: 1100, rarity: "N" },
  { id: "stb-war-earth", name: "ウォー・アース", cardType: "monster", kind: "岩石族", attribute: "地", level: 3, atk: 700, def: 1400, rarity: "N" },
  { id: "stb-ancient-tree", name: "悟りの老樹", cardType: "monster", kind: "植物族", attribute: "地", level: 3, atk: 600, def: 1500, rarity: "N" },
  { id: "stb-green-phantom-king", name: "緑樹の霊王", cardType: "monster", kind: "植物族", attribute: "地", level: 3, atk: 500, def: 1600, rarity: "N" },
  { id: "stb-north-wind-sun", name: "北風と太陽", cardType: "monster", kind: "天使族", attribute: "光", level: 3, atk: 1000, def: 1000, rarity: "N" },
  { id: "stb-king-smoke", name: "キング・スモーク", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 3, atk: 1000, def: 900, rarity: "N" },
  { id: "stb-sleepy", name: "スリーピィ", cardType: "monster", kind: "獣族", attribute: "地", level: 3, atk: 800, def: 1000, rarity: "N" },
  { id: "stb-devil-snake", name: "デビル・スネーク", cardType: "monster", kind: "爬虫類族", attribute: "地", level: 2, atk: 700, def: 600, rarity: "N" },
  { id: "stb-change-slime", name: "チェンジ・スライム", cardType: "monster", kind: "水族", attribute: "水", level: 1, atk: 400, def: 300, rarity: "N" },
  { id: "stb-masaki", name: "伝説の剣豪 MASAKI", cardType: "monster", kind: "戦士族", attribute: "地", level: 4, atk: 1100, def: 1100, rarity: "N" },
  { id: "stb-dragon-capture-jar", name: "ドラゴン族・封印の壺", cardType: "trap", kind: "永続罠", rarity: "N" },
  { id: "stb-forest", name: "森", cardType: "spell", kind: "フィールド魔法", rarity: "R" },
  { id: "stb-wasteland", name: "荒野", cardType: "spell", kind: "フィールド魔法", rarity: "R" },
  { id: "stb-mountain", name: "山", cardType: "spell", kind: "フィールド魔法", rarity: "SR" },
  { id: "stb-sogen", name: "草原", cardType: "spell", kind: "フィールド魔法", rarity: "R" },
  { id: "stb-umi", name: "海", cardType: "spell", kind: "フィールド魔法", rarity: "R" },
  { id: "stb-yami", name: "闇", cardType: "spell", kind: "フィールド魔法", rarity: "R" },
  { id: "stb-raigeki", name: "サンダー・ボルト", cardType: "spell", kind: "通常魔法", rarity: "SR" },
  { id: "stb-moyan-curry", name: "モウヤンのカレー", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "stb-fireball", name: "ファイヤー・ボール", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "stb-polymerization", name: "融合", cardType: "spell", kind: "通常魔法", rarity: "SR" },
  { id: "stb-remove-trap", name: "罠はずし", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "stb-two-pronged-attack", name: "はさみ撃ち", cardType: "trap", kind: "通常罠", rarity: "N" },
];

const boosterOneIds = [
  ...earlyProductCards.filter((card) => card.id.startsWith("bo1-")).map((card) => card.id),
  "vol1-legendary-sword",
  "vol1-beast-fangs",
  "vol1-violet-crystal",
  "vol1-book-secret-arts",
  "vol1-power-kaishin",
];

const starterBoxIds = earlyProductCards.filter((card) => card.id.startsWith("stb-")).map((card) => card.id);

export const earlyProductPacks: Pack[] = [
  { id: "booster-1", name: "Booster 1", releaseDate: "1999-03-01", category: "official", cardIds: boosterOneIds },
  { id: "starter-box", name: "STARTER BOX", releaseDate: "1999-03-18", category: "official", cardIds: starterBoxIds },
];
