import type { Card, Pack } from "./card-data";

export const magicRulerCards: Card[] = [
  { id: "mr-penguin-knight", name: "ペンギン・ナイト", cardType: "monster", kind: "水族", attribute: "水", level: 3, atk: 900, def: 800, rarity: "N", effect: true },
  { id: "mr-axe-despair", name: "デーモンの斧", cardType: "spell", kind: "装備魔法", rarity: "SR" },
  { id: "mr-black-pendant", name: "黒いペンダント", cardType: "spell", kind: "装備魔法", rarity: "R" },
  { id: "mr-horn-light", name: "光の角", cardType: "spell", kind: "装備魔法", rarity: "N" },
  { id: "mr-malevolent-nuzzler", name: "悪魔のくちづけ", cardType: "spell", kind: "装備魔法", rarity: "N" },
  { id: "mr-spellbinding-circle", name: "六芒星の呪縛", cardType: "trap", kind: "永続罠", rarity: "UR" },
  { id: "mr-metal-fish", name: "メタル・フィッシュ", cardType: "monster", kind: "機械族", attribute: "水", level: 5, atk: 1600, def: 1900, rarity: "N" },
  { id: "mr-electric-snake", name: "エレクトリック・スネーク", cardType: "monster", kind: "雷族", attribute: "光", level: 3, atk: 800, def: 900, rarity: "N", effect: true },
  { id: "mr-queen-bird", name: "クイーン・バード", cardType: "monster", kind: "鳥獣族", attribute: "風", level: 5, atk: 1200, def: 2000, rarity: "N" },
  { id: "mr-ameba", name: "アメーバ", cardType: "monster", kind: "水族", attribute: "水", level: 1, atk: 300, def: 350, rarity: "N", effect: true },
  { id: "mr-peacock", name: "クジャック", cardType: "monster", kind: "鳥獣族", attribute: "風", level: 5, atk: 1700, def: 1500, rarity: "N" },
  { id: "mr-maha-vailo", name: "マハー・ヴァイロ", cardType: "monster", kind: "魔法使い族", attribute: "光", level: 4, atk: 1550, def: 1400, rarity: "N", effect: true },
  { id: "mr-throne-room-guardian", name: "王室前のガーディアン", cardType: "monster", kind: "機械族", attribute: "光", level: 4, atk: 1650, def: 1600, rarity: "N" },
  { id: "mr-fire-kraken", name: "ファイヤー・クラーケン", cardType: "monster", kind: "水族", attribute: "炎", level: 4, atk: 1600, def: 1500, rarity: "N" },
  { id: "mr-minar", name: "イビー", cardType: "monster", kind: "昆虫族", attribute: "地", level: 3, atk: 850, def: 750, rarity: "N", effect: true },
  { id: "mr-griggle", name: "グリグル", cardType: "monster", kind: "植物族", attribute: "地", level: 1, atk: 350, def: 300, rarity: "N", effect: true },
  { id: "mr-red-dragon", name: "レッド・ドラゴン", cardType: "monster", kind: "ドラゴン族", attribute: "炎", level: 6, atk: 1700, def: 1900, rarity: "N" },
  { id: "mr-deep-forest-elder", name: "深き森の長老", cardType: "monster", kind: "獣族", attribute: "地", level: 6, atk: 1800, def: 1900, rarity: "N" },
  { id: "mr-valkyrie", name: "ヴァルキリー", cardType: "monster", kind: "天使族", attribute: "光", level: 5, atk: 1800, def: 1700, rarity: "N" },
  { id: "mr-weather-report", name: "ウェザー・レポート", cardType: "monster", kind: "水族", attribute: "水", level: 4, atk: 950, def: 1500, rarity: "N", effect: true },
  { id: "mr-mechanical-snail", name: "メカニカルスネイル", cardType: "monster", kind: "機械族", attribute: "闇", level: 3, atk: 800, def: 1000, rarity: "N" },
  { id: "mr-flame-eating-turtle", name: "炎を食らう大亀", cardType: "monster", kind: "水族", attribute: "水", level: 5, atk: 1400, def: 1800, rarity: "N" },
  { id: "mr-liquid-beast", name: "リクイド・ビースト", cardType: "monster", kind: "水族", attribute: "水", level: 3, atk: 950, def: 800, rarity: "N" },
  { id: "mr-hiros-shadow-scout", name: "悪魔の偵察者", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 2, atk: 650, def: 500, rarity: "SR", effect: true },
  { id: "mr-high-tide-gyojin", name: "満ち潮のマーマン", cardType: "monster", kind: "水族", attribute: "水", level: 4, atk: 1650, def: 1300, rarity: "N" },
  { id: "mr-invader-throne", name: "王座の侵略者", cardType: "monster", kind: "戦士族", attribute: "地", level: 4, atk: 1350, def: 1700, rarity: "SR", effect: true },
  { id: "mr-whiptail-gargoyle", name: "ウィップテイル・ガーゴイル", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 4, atk: 1650, def: 1600, rarity: "N" },
  { id: "mr-slot-machine", name: "スロットマシーンAM－７", cardType: "monster", kind: "機械族", attribute: "闇", level: 7, atk: 2000, def: 2300, rarity: "UR" },
  { id: "mr-relinquished", name: "サクリファイス", cardType: "monster", kind: "魔法使い族", attribute: "闇", level: 1, atk: 0, def: 0, rarity: "UR", effect: true },
  { id: "mr-mermaid-archer", name: "弓を引くマーメイド", cardType: "monster", kind: "水族", attribute: "水", level: 4, atk: 1400, def: 1500, rarity: "N" },
  { id: "mr-gravekeepers-servant", name: "墓守の使い魔", cardType: "spell", kind: "永続魔法", rarity: "N" },
  { id: "mr-curse-fiend", name: "邪悪な儀式", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "mr-upstart-goblin", name: "成金ゴブリン", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "mr-toll", name: "通行税", cardType: "spell", kind: "永続魔法", rarity: "R" },
  { id: "mr-final-destiny", name: "最終戦争", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "mr-snatch-steal", name: "強奪", cardType: "spell", kind: "装備魔法", rarity: "N" },
  { id: "mr-chorus-sanctuary", name: "聖域の歌声", cardType: "spell", kind: "フィールド魔法", rarity: "N" },
  { id: "mr-confiscation", name: "押収", cardType: "spell", kind: "通常魔法", rarity: "R" },
  { id: "mr-delinquent-duo", name: "いたずら好きな双子悪魔", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "mr-darkness-approaches", name: "闇の訪れ", cardType: "spell", kind: "通常魔法", rarity: "R" },
  { id: "mr-fairys-hand-mirror", name: "天使の手鏡", cardType: "trap", kind: "通常罠", rarity: "N" },
  { id: "mr-tailor-fickle", name: "移り気な仕立屋", cardType: "spell", kind: "速攻魔法", rarity: "N" },
  { id: "mr-rush-recklessly", name: "突進", cardType: "spell", kind: "速攻魔法", rarity: "N" },
  { id: "mr-reliable-guardian", name: "頼もしき守護者", cardType: "spell", kind: "速攻魔法", rarity: "N" },
  { id: "mr-forceful-sentry", name: "強引な番兵", cardType: "spell", kind: "通常魔法", rarity: "SR" },
  { id: "mr-chain-energy", name: "魔力の枷", cardType: "spell", kind: "永続魔法", rarity: "N" },
  { id: "mr-mystical-space-typhoon", name: "サイクロン", cardType: "spell", kind: "速攻魔法", rarity: "N" },
  { id: "mr-giant-trunade", name: "ハリケーン", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "mr-painful-choice", name: "苦渋の選択", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "mr-snake-fang", name: "毒蛇の牙", cardType: "trap", kind: "通常罠", rarity: "N" },
];

export const magicRulerPack: Pack = {
  id: "magic-ruler",
  name: "Magic Ruler －魔法の支配者－",
  releaseDate: "2000-04-20",
  category: "official",
  cardIds: magicRulerCards.map((card) => card.id),
};
