import type { Card, Pack } from "./card-data";

// 次弾準備データ。効果処理が揃うまで card-data.ts には登録しない。
export const pharaohsServantCards: Card[] = [
  { id: "ps-00", name: "ブルーアイズ・トゥーン・ドラゴン", cardType: "monster", kind: "ドラゴン族", attribute: "光", level: 8, atk: 3000, def: 2500, rarity: "SE", effect: true },
  { id: "ps-01", name: "オクトバーサー", cardType: "monster", kind: "水族", attribute: "水", level: 5, atk: 1600, def: 1400, rarity: "N" },
  { id: "ps-02", name: "サイコ・カッパー", cardType: "monster", kind: "水族", attribute: "水", level: 2, atk: 400, def: 1000, rarity: "N" },
  { id: "ps-03", name: "一角獣のホーン", cardType: "spell", kind: "装備魔法", rarity: "SR" },
  { id: "ps-04", name: "迷宮壁－ラビリンス・ウォール－", cardType: "monster", kind: "岩石族", attribute: "地", level: 5, atk: 0, def: 3000, rarity: "N" },
  { id: "ps-05", name: "ウォール・シャドウ", cardType: "monster", kind: "戦士族", attribute: "闇", level: 7, atk: 1600, def: 3000, rarity: "N", effect: true },
  { id: "ps-06", name: "ツインテール", cardType: "monster", kind: "水族", attribute: "水", level: 3, atk: 850, def: 700, rarity: "N" },
  { id: "ps-07", name: "ストーンジャイアント", cardType: "monster", kind: "岩石族", attribute: "地", level: 5, atk: 1600, def: 1500, rarity: "N" },
  { id: "ps-08", name: "迷宮変化", cardType: "spell", kind: "装備魔法", rarity: "N" },
  { id: "ps-09", name: "成仏", cardType: "spell", kind: "通常魔法", rarity: "R" },
  { id: "ps-10", name: "巨大化", cardType: "spell", kind: "装備魔法", rarity: "R" },
  { id: "ps-11", name: "踊りによる誘発", cardType: "spell", kind: "儀式魔法", rarity: "N" },
  { id: "ps-12", name: "ハンバーガーのレシピ", cardType: "spell", kind: "儀式魔法", rarity: "N" },
  { id: "ps-13", name: "粘着テープの家", cardType: "trap", kind: "通常罠", rarity: "N" },
  { id: "ps-14", name: "ねずみ取り", cardType: "trap", kind: "通常罠", rarity: "N" },
  { id: "ps-15", name: "亀の誓い", cardType: "spell", kind: "儀式魔法", rarity: "N" },
  { id: "ps-16", name: "ダンシング・ソルジャー", cardType: "monster", kind: "戦士族", attribute: "地", level: 6, atk: 1950, def: 1850, rarity: "N", ritual: true },
  { id: "ps-17", name: "ハングリーバーガー", cardType: "monster", kind: "戦士族", attribute: "闇", level: 6, atk: 2000, def: 1850, rarity: "N", ritual: true },
  { id: "ps-18", name: "クラブ・タートル", cardType: "monster", kind: "水族", attribute: "水", level: 8, atk: 2550, def: 2500, rarity: "N", ritual: true },
  { id: "ps-19", name: "ドラゴン・エッガー", cardType: "monster", kind: "ドラゴン族", attribute: "炎", level: 7, atk: 2200, def: 2600, rarity: "N" },
  { id: "ps-20", name: "トゥーン・ドラゴン・エッガー", cardType: "monster", kind: "ドラゴン族", attribute: "炎", level: 7, atk: 2200, def: 2600, rarity: "N", effect: true },
  { id: "ps-21", name: "トゥーン・マーメイド", cardType: "monster", kind: "水族", attribute: "水", level: 4, atk: 1400, def: 1500, rarity: "SR", effect: true },
  { id: "ps-22", name: "トゥーン・デーモン", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 6, atk: 2500, def: 1200, rarity: "UR", effect: true },
  { id: "ps-23", name: "タイム・ボマー", cardType: "monster", kind: "炎族", attribute: "炎", level: 2, atk: 200, def: 1000, rarity: "R", effect: true },
  { id: "ps-24", name: "ダイヤモンド・ドラゴン", cardType: "monster", kind: "ドラゴン族", attribute: "光", level: 7, atk: 2100, def: 2800, rarity: "UR" },
  { id: "ps-25", name: "トゥーン・ワールド", cardType: "spell", kind: "永続魔法", rarity: "UR" },
  { id: "ps-26", name: "サイバーポッド", cardType: "monster", kind: "岩石族", attribute: "闇", level: 3, atk: 900, def: 900, rarity: "N", effect: true },
  { id: "ps-27", name: "光の追放者", cardType: "monster", kind: "天使族", attribute: "光", level: 3, atk: 100, def: 2000, rarity: "R", effect: true },
  { id: "ps-28", name: "巨大ネズミ", cardType: "monster", kind: "獣族", attribute: "地", level: 4, atk: 1400, def: 1450, rarity: "N", effect: true },
  { id: "ps-29", name: "センジュ・ゴッド", cardType: "monster", kind: "天使族", attribute: "光", level: 4, atk: 1400, def: 1000, rarity: "SR", effect: true },
  { id: "ps-30", name: "UFOタートル", cardType: "monster", kind: "機械族", attribute: "炎", level: 4, atk: 1400, def: 1200, rarity: "N", effect: true },
  { id: "ps-31", name: "秒殺の暗殺者", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 4, atk: 2000, def: 2000, rarity: "N", effect: true },
  { id: "ps-32", name: "カラテマン", cardType: "monster", kind: "戦士族", attribute: "地", level: 3, atk: 1000, def: 1000, rarity: "N", effect: true },
  { id: "ps-33", name: "ダークゼブラ", cardType: "monster", kind: "獣族", attribute: "地", level: 4, atk: 1800, def: 400, rarity: "N", effect: true },
  { id: "ps-34", name: "ジャイアントウィルス", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 2, atk: 1000, def: 100, rarity: "R", effect: true },
  { id: "ps-35", name: "素早いモモンガ", cardType: "monster", kind: "獣族", attribute: "地", level: 2, atk: 1000, def: 100, rarity: "R", effect: true },
  { id: "ps-36", name: "ダークファミリア", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 2, atk: 500, def: 500, rarity: "N", effect: true },
  { id: "ps-37", name: "シャインエンジェル", cardType: "monster", kind: "天使族", attribute: "光", level: 4, atk: 1400, def: 800, rarity: "N", effect: true },
  { id: "ps-38", name: "ボアソルジャー", cardType: "monster", kind: "獣戦士族", attribute: "地", level: 4, atk: 2000, def: 500, rarity: "N", effect: true },
  { id: "ps-39", name: "グリズリーマザー", cardType: "monster", kind: "獣戦士族", attribute: "水", level: 4, atk: 1400, def: 1000, rarity: "N", effect: true },
  { id: "ps-40", name: "ドラゴンフライ", cardType: "monster", kind: "昆虫族", attribute: "風", level: 4, atk: 1400, def: 900, rarity: "N", effect: true },
  { id: "ps-41", name: "セレモニーベル", cardType: "monster", kind: "魔法使い族", attribute: "光", level: 3, atk: 0, def: 1850, rarity: "N", effect: true },
  { id: "ps-42", name: "ソニックバード", cardType: "monster", kind: "鳥獣族", attribute: "風", level: 4, atk: 1400, def: 1000, rarity: "N", effect: true },
  { id: "ps-43", name: "キラー・トマト", cardType: "monster", kind: "植物族", attribute: "闇", level: 4, atk: 1400, def: 1100, rarity: "N", effect: true },
  { id: "ps-44", name: "コトダマ", cardType: "monster", kind: "天使族", attribute: "地", level: 3, atk: 0, def: 1600, rarity: "N", effect: true },
  { id: "ps-45", name: "ガイアパワー", cardType: "spell", kind: "フィールド魔法", rarity: "N" },
  { id: "ps-46", name: "ウォーターワールド", cardType: "spell", kind: "フィールド魔法", rarity: "N" },
  { id: "ps-47", name: "バーニングブラッド", cardType: "spell", kind: "フィールド魔法", rarity: "N" },
  { id: "ps-48", name: "デザートストーム", cardType: "spell", kind: "フィールド魔法", rarity: "N" },
  { id: "ps-49", name: "シャインスパーク", cardType: "spell", kind: "フィールド魔法", rarity: "N" },
  { id: "ps-50", name: "ダークゾーン", cardType: "spell", kind: "フィールド魔法", rarity: "N" },
  { id: "ps-51", name: "平和の使者", cardType: "spell", kind: "永続魔法", rarity: "SR" },
];

export const pharaohsServantPackDraft: Pack = {
  id: "pharaohs-servant",
  name: "Pharaoh's Servant －ファラオのしもべ－",
  releaseDate: "2000-07-13",
  category: "official",
  cardIds: pharaohsServantCards.map((card) => card.id),
};
