import type { Card, Pack } from "./card-data";

// 2000年12月14日発売時の全52種類。
export const thousandEyesBibleCards: Card[] = [
  { id: "tb-01", name: "道連れ", cardType: "trap", kind: "通常罠", rarity: "R" },
  { id: "tb-02", name: "ゴブリンの小役人", cardType: "trap", kind: "永続罠", rarity: "N" },
  { id: "tb-03", name: "ギャンブル", cardType: "trap", kind: "通常罠", rarity: "N" },
  { id: "tb-04", name: "白兵戦", cardType: "trap", kind: "通常罠", rarity: "R" },
  { id: "tb-05", name: "神の恵み", cardType: "trap", kind: "永続罠", rarity: "N" },
  { id: "tb-06", name: "死霊の誘い", cardType: "trap", kind: "永続罠", rarity: "N" },
  { id: "tb-07", name: "デスハムスター", cardType: "monster", kind: "獣族", attribute: "地", level: 3, atk: 900, def: 600, rarity: "N", effect: true },
  { id: "tb-08", name: "ダークバット", cardType: "monster", kind: "鳥獣族", attribute: "風", level: 3, atk: 1000, def: 1000, rarity: "N" },
  { id: "tb-09", name: "鬼タンクＴ－３４", cardType: "monster", kind: "機械族", attribute: "地", level: 4, atk: 1400, def: 1700, rarity: "N" },
  { id: "tb-10", name: "ガトリングバギー", cardType: "monster", kind: "機械族", attribute: "地", level: 4, atk: 1600, def: 1500, rarity: "N" },
  { id: "tb-11", name: "燃えさかる大地", cardType: "spell", kind: "永続魔法", rarity: "N" },
  { id: "tb-12", name: "大寒波", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "tb-13", name: "メテオ・ストライク", cardType: "spell", kind: "装備魔法", rarity: "N" },
  { id: "tb-14", name: "リミッター解除", cardType: "spell", kind: "速攻魔法", rarity: "N" },
  { id: "tb-15", name: "恵みの雨", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "tb-16", name: "モンスター回収", cardType: "spell", kind: "速攻魔法", rarity: "SR" },
  { id: "tb-17", name: "シフトチェンジ", cardType: "trap", kind: "通常罠", rarity: "UR" },
  { id: "tb-18", name: "孵化", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "tb-19", name: "ワーム・ホール", cardType: "spell", kind: "通常魔法", rarity: "R" },
  { id: "tb-20", name: "地盤沈下", cardType: "spell", kind: "永続魔法", rarity: "N" },
  { id: "tb-21", name: "マジック・ドレイン", cardType: "trap", kind: "カウンター罠", rarity: "SR" },
  { id: "tb-22", name: "メサイアの蟻地獄", cardType: "trap", kind: "永続罠", rarity: "N" },
  { id: "tb-23", name: "グラヴィティ・バインド－超重力の網－", cardType: "trap", kind: "永続罠", rarity: "N" },
  { id: "tb-24", name: "零式魔導粉砕機", cardType: "trap", kind: "永続罠", rarity: "N" },
  { id: "tb-25", name: "誘惑のシャドウ", cardType: "trap", kind: "通常罠", rarity: "R" },
  { id: "tb-26", name: "伝説のフィッシャーマン", cardType: "monster", kind: "戦士族", attribute: "水", level: 5, atk: 1850, def: 1600, rarity: "SR", effect: true },
  { id: "tb-27", name: "ソードハンター", cardType: "monster", kind: "戦士族", attribute: "地", level: 7, atk: 2450, def: 1700, rarity: "N", effect: true },
  { id: "tb-28", name: "穿孔虫", cardType: "monster", kind: "昆虫族", attribute: "地", level: 2, atk: 1100, def: 200, rarity: "N", effect: true },
  { id: "tb-29", name: "深海の戦士", cardType: "monster", kind: "戦士族", attribute: "水", level: 5, atk: 1600, def: 1800, rarity: "N", effect: true },
  { id: "tb-30", name: "朱い靴", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 2, atk: 500, def: 300, rarity: "N", effect: true },
  { id: "tb-31", name: "スパイク・ヘッド", cardType: "monster", kind: "機械族", attribute: "闇", level: 5, atk: 1800, def: 1700, rarity: "N" },
  { id: "tb-32", name: "暗黒の眠りを誘うルシファー", cardType: "monster", kind: "魔法使い族", attribute: "闇", level: 5, atk: 1500, def: 1800, rarity: "R", effect: true },
  { id: "tb-33", name: "千眼の邪教神", cardType: "monster", kind: "魔法使い族", attribute: "闇", level: 1, atk: 0, def: 0, rarity: "N" },
  { id: "tb-34", name: "サウザンド・アイズ・サクリファイス", cardType: "monster", kind: "魔法使い族", attribute: "闇", level: 1, atk: 0, def: 0, rarity: "UR", fusion: true, effect: true },
  { id: "tb-35", name: "ギロチン・クワガタ", cardType: "monster", kind: "昆虫族", attribute: "風", level: 4, atk: 1700, def: 1000, rarity: "N" },
  { id: "tb-36", name: "隼の騎士", cardType: "monster", kind: "戦士族", attribute: "地", level: 3, atk: 1000, def: 700, rarity: "N", effect: true },
  { id: "tb-37", name: "爆弾かめ虫", cardType: "monster", kind: "昆虫族", attribute: "風", level: 2, atk: 400, def: 900, rarity: "N", effect: true },
  { id: "tb-38", name: "死の４つ星てんとう虫", cardType: "monster", kind: "昆虫族", attribute: "風", level: 3, atk: 800, def: 1200, rarity: "N", effect: true },
  { id: "tb-39", name: "超時空戦闘機ビック・バイパー", cardType: "monster", kind: "機械族", attribute: "光", level: 4, atk: 1200, def: 800, rarity: "N" },
  { id: "tb-40", name: "ヴァンパイア・ベビー", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 3, atk: 700, def: 1000, rarity: "N", effect: true },
  { id: "tb-41", name: "猛進する剣角獣", cardType: "monster", kind: "恐竜族", attribute: "地", level: 4, atk: 1400, def: 1200, rarity: "N", effect: true },
  { id: "tb-42", name: "海賊船スカルブラッド号", cardType: "monster", kind: "戦士族", attribute: "水", level: 4, atk: 1600, def: 900, rarity: "N" },
  { id: "tb-43", name: "隻眼のホワイトタイガー", cardType: "monster", kind: "獣族", attribute: "風", level: 3, atk: 1300, def: 500, rarity: "N" },
  { id: "tb-44", name: "ゴブリン突撃部隊", cardType: "monster", kind: "戦士族", attribute: "地", level: 4, atk: 2300, def: 0, rarity: "N", effect: true },
  { id: "tb-45", name: "島亀", cardType: "monster", kind: "水族", attribute: "水", level: 4, atk: 1100, def: 2000, rarity: "N" },
  { id: "tb-46", name: "翼を織りなす者", cardType: "monster", kind: "天使族", attribute: "光", level: 7, atk: 2750, def: 2400, rarity: "N" },
  { id: "tb-47", name: "科学特殊兵", cardType: "monster", kind: "戦士族", attribute: "闇", level: 3, atk: 800, def: 800, rarity: "N" },
  { id: "tb-48", name: "怨念集合体", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 2, atk: 900, def: 200, rarity: "N" },
  { id: "tb-49", name: "死神ブーメラン", cardType: "monster", kind: "悪魔族", attribute: "炎", level: 3, atk: 1000, def: 400, rarity: "N" },
  { id: "tb-50", name: "魔導ギガサイバー", cardType: "monster", kind: "戦士族", attribute: "闇", level: 6, atk: 2200, def: 1200, rarity: "UR", effect: true },
  { id: "tb-51", name: "鉄の騎士 ギア・フリード", cardType: "monster", kind: "戦士族", attribute: "地", level: 4, atk: 1800, def: 1600, rarity: "SR", effect: true },
  { id: "tb-52", name: "虫除けバリアー", cardType: "spell", kind: "永続魔法", rarity: "R" },
];

export const thousandEyesBiblePack: Pack = {
  id: "thousand-eyes-bible",
  name: "Thousand Eyes Bible －千眼の魔術書－",
  releaseDate: "2000-12-14",
  category: "official",
  cardIds: thousandEyesBibleCards.map((card) => card.id),
};

// 基本情報とテキストは全52種。ここには対戦処理まで接続済みのカードを列挙する。
export const thousandEyesBibleReadyCardIds = [
  "tb-02", "tb-05", "tb-06", "tb-07", "tb-08", "tb-09", "tb-10", "tb-11", "tb-13", "tb-14", "tb-15", "tb-22", "tb-23", "tb-27", "tb-28", "tb-30", "tb-31", "tb-33", "tb-35", "tb-36", "tb-37", "tb-38", "tb-39", "tb-40", "tb-41", "tb-42", "tb-43", "tb-44", "tb-45", "tb-46", "tb-47", "tb-48", "tb-49", "tb-50", "tb-51", "tb-52",
] as const;
