import type { Card } from "./card-data";

export const vol5Cards: Card[] = [
  { id: "vol5-feral-imp", name: "グレムリン", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 4, atk: 1300, def: 1400, rarity: "N" },
  { id: "vol5-killer-needle", name: "キラー・ビー", cardType: "monster", kind: "昆虫族", attribute: "風", level: 4, atk: 1200, def: 1000, rarity: "N" },
  { id: "vol5-larvae-moth", name: "ラーバモス", cardType: "monster", kind: "昆虫族", attribute: "地", level: 2, atk: 500, def: 400, rarity: "N", effect: true },
  { id: "vol5-armored-zombie", name: "鎧武者ゾンビ", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 3, atk: 1500, def: 0, rarity: "N" },
  { id: "vol5-white-magical-hat", name: "白い泥棒", cardType: "monster", kind: "魔法使い族", attribute: "光", level: 3, atk: 1000, def: 700, rarity: "N", effect: true },
  { id: "vol5-toad-master", name: "トードマスター", cardType: "monster", kind: "水族", attribute: "水", level: 3, atk: 1000, def: 1000, rarity: "N" },
  { id: "vol5-big-eye", name: "大王目玉", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 4, atk: 1200, def: 1000, rarity: "N", effect: true },
  { id: "vol5-dark-shade", name: "ダークシェイド", cardType: "monster", kind: "悪魔族", attribute: "風", level: 3, atk: 1000, def: 1000, rarity: "N" },
  { id: "vol5-black-skull-dragon", name: "ブラック・デーモンズ・ドラゴン", cardType: "monster", kind: "ドラゴン族", attribute: "闇", level: 9, atk: 3200, def: 2500, rarity: "UR", fusion: true },
  { id: "vol5-masked-sorcerer", name: "仮面魔道士", cardType: "monster", kind: "魔法使い族", attribute: "闇", level: 4, atk: 900, def: 1400, rarity: "N", effect: true },
  { id: "vol5-roaring-ocean-snake", name: "轟きの大海蛇", cardType: "monster", kind: "水族", attribute: "水", level: 6, atk: 2100, def: 1800, rarity: "N", fusion: true },
  { id: "vol5-master-expert", name: "マスター・アン・エキスパート", cardType: "monster", kind: "獣族", attribute: "地", level: 4, atk: 1200, def: 1000, rarity: "N" },
  { id: "vol5-hyo", name: "氷", cardType: "monster", kind: "戦士族", attribute: "水", level: 3, atk: 800, def: 1200, rarity: "N" },
  { id: "vol5-wing-egg-elf", name: "ウィング・エッグ・エルフ", cardType: "monster", kind: "天使族", attribute: "光", level: 3, atk: 500, def: 1300, rarity: "N" },
  { id: "vol5-unknown-warrior", name: "悪の無名戦士", cardType: "monster", kind: "戦士族", attribute: "闇", level: 3, atk: 1000, def: 500, rarity: "N" },
  { id: "vol5-bio-plant", name: "Ｂ・プラント", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 3, atk: 600, def: 1300, rarity: "N" },
  { id: "vol5-sanga", name: "雷魔神－サンガ", cardType: "monster", kind: "雷族", attribute: "光", level: 7, atk: 2600, def: 2200, rarity: "SR", effect: true },
  { id: "vol5-kazejin", name: "風魔神－ヒューガ", cardType: "monster", kind: "魔法使い族", attribute: "風", level: 7, atk: 2400, def: 2200, rarity: "SR", effect: true },
  { id: "vol5-suijin", name: "水魔神－スーガ", cardType: "monster", kind: "水族", attribute: "水", level: 7, atk: 2500, def: 2400, rarity: "SR", effect: true },
  { id: "vol5-dungeon-worm", name: "ダンジョン・ワーム", cardType: "monster", kind: "昆虫族", attribute: "地", level: 5, atk: 1800, def: 1500, rarity: "R" },
  { id: "vol5-rude-kaiser", name: "ルード・カイザー", cardType: "monster", kind: "獣戦士族", attribute: "地", level: 5, atk: 1800, def: 1600, rarity: "R" },
  { id: "vol5-dark-rabbit", name: "ダーク・ラビット", cardType: "monster", kind: "獣族", attribute: "闇", level: 4, atk: 1100, def: 1500, rarity: "N" },
  { id: "vol5-mystic-lamp", name: "魔法のランプ", cardType: "monster", kind: "魔法使い族", attribute: "闇", level: 1, atk: 400, def: 300, rarity: "N", effect: true },
  { id: "vol5-leghul", name: "レッグル", cardType: "monster", kind: "昆虫族", attribute: "地", level: 1, atk: 300, def: 350, rarity: "N", effect: true },
  { id: "vol5-ooguchi", name: "ラージマウス", cardType: "monster", kind: "水族", attribute: "水", level: 1, atk: 300, def: 250, rarity: "N", effect: true },
  { id: "vol5-leogun", name: "レオグン", cardType: "monster", kind: "獣族", attribute: "地", level: 5, atk: 1750, def: 1550, rarity: "N" },
  { id: "vol5-yaiba-robo", name: "カッター・ロボ", cardType: "monster", kind: "機械族", attribute: "闇", level: 4, atk: 1000, def: 1300, rarity: "N" },
  { id: "vol5-blast-juggler", name: "ミスター・ボンバー", cardType: "monster", kind: "機械族", attribute: "炎", level: 3, atk: 800, def: 900, rarity: "N", effect: true },
  { id: "vol5-jinzo-7", name: "人造人間７号", cardType: "monster", kind: "機械族", attribute: "闇", level: 2, atk: 500, def: 400, rarity: "N", effect: true },
  { id: "vol5-magical-ghost", name: "マジカル・ゴースト", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 4, atk: 1300, def: 1400, rarity: "N" },
  { id: "vol5-rainbow-flower", name: "レインボー・フラワー", cardType: "monster", kind: "植物族", attribute: "地", level: 2, atk: 400, def: 500, rarity: "N", effect: true },
  { id: "vol5-empress-judge", name: "裁きを下す女帝", cardType: "monster", kind: "戦士族", attribute: "地", level: 6, atk: 2100, def: 1700, rarity: "N", fusion: true },
  { id: "vol5-crow-goblin", name: "カラス天狗", cardType: "monster", kind: "鳥獣族", attribute: "風", level: 5, atk: 1850, def: 1600, rarity: "R" },
  { id: "vol5-rose-spectre", name: "バラに棲む悪霊", cardType: "monster", kind: "植物族", attribute: "闇", level: 6, atk: 2000, def: 1800, rarity: "N", fusion: true },
  { id: "vol5-pale-beast", name: "ペイルビースト", cardType: "monster", kind: "獣族", attribute: "地", level: 4, atk: 1500, def: 1200, rarity: "N" },
  { id: "vol5-snakeyashi", name: "スネーク・パーム", cardType: "monster", kind: "植物族", attribute: "地", level: 4, atk: 1000, def: 1200, rarity: "N" },
  { id: "vol5-mud-thing", name: "泥に潜み棲むもの", cardType: "monster", kind: "岩石族", attribute: "地", level: 4, atk: 1200, def: 1300, rarity: "N" },
  { id: "vol5-armored-rat", name: "鎧ネズミ", cardType: "monster", kind: "獣族", attribute: "地", level: 3, atk: 950, def: 1100, rarity: "N" },
  { id: "vol5-queens-double", name: "女王の影武者", cardType: "monster", kind: "戦士族", attribute: "地", level: 1, atk: 350, def: 300, rarity: "N", effect: true },
  { id: "vol5-acid-crawler", name: "アシッドクロウラー", cardType: "monster", kind: "昆虫族", attribute: "地", level: 3, atk: 900, def: 700, rarity: "N" },
  { id: "vol5-disk-magician", name: "ディスク・マジシャン", cardType: "monster", kind: "機械族", attribute: "闇", level: 4, atk: 1350, def: 1000, rarity: "N" },
  { id: "vol5-hyosube", name: "ひょうすべ", cardType: "monster", kind: "水族", attribute: "水", level: 4, atk: 1500, def: 900, rarity: "N" },
  { id: "vol5-hibikime", name: "響女", cardType: "monster", kind: "戦士族", attribute: "地", level: 4, atk: 1450, def: 1000, rarity: "N" },
  { id: "vol5-tribute-doomed", name: "死者への手向け", cardType: "spell", kind: "通常魔法", rarity: "UR" },
  { id: "vol5-soul-release", name: "魂の解放", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "vol5-cheerful-coffin", name: "陽気な葬儀屋", cardType: "spell", kind: "通常魔法", rarity: "UR" },
  { id: "vol5-change-heart", name: "心変わり", cardType: "spell", kind: "通常魔法", rarity: "UR" },
  { id: "vol5-fake-trap", name: "偽物のわな", cardType: "trap", kind: "通常罠", rarity: "N" },
  { id: "vol5-anti-raigeki", name: "避雷針", cardType: "trap", kind: "通常罠", rarity: "R" },
  { id: "vol5-call-darkness", name: "闇からの呼び声", cardType: "trap", kind: "永続罠", rarity: "R" },
];
