import type { Card } from "./card-data";

// 1999年11月18日発売「Vol.6」全52種類。
// グレート・モスと千年竜は当時の最高レア仕様をSEとして収録する。
export const vol6Cards: Card[] = [
  { id: "vol6-baby-dragon", name: "ベビードラゴン", cardType: "monster", kind: "ドラゴン族", attribute: "風", level: 3, atk: 1200, def: 700, rarity: "N" },
  { id: "vol6-blackland-fire-dragon", name: "暗黒の竜王", cardType: "monster", kind: "ドラゴン族", attribute: "闇", level: 4, atk: 1500, def: 800, rarity: "N" },
  { id: "vol6-battle-steer", name: "牛魔人", cardType: "monster", kind: "獣戦士族", attribute: "地", level: 5, atk: 1800, def: 1300, rarity: "N" },
  { id: "vol6-horn-imp", name: "インプ", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 4, atk: 1300, def: 1000, rarity: "N" },
  { id: "vol6-dragon-piper", name: "壺魔人", cardType: "monster", kind: "炎族", attribute: "炎", level: 3, atk: 200, def: 1800, rarity: "N", effect: true },
  { id: "vol6-griffore", name: "グリフォール", cardType: "monster", kind: "獣族", attribute: "地", level: 4, atk: 1200, def: 1500, rarity: "N" },
  { id: "vol6-torike", name: "サイガー", cardType: "monster", kind: "獣族", attribute: "地", level: 3, atk: 1200, def: 600, rarity: "N" },
  { id: "vol6-sangan", name: "クリッター", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 3, atk: 1000, def: 600, rarity: "N", effect: true },
  { id: "vol6-gokibore", name: "ゴキボール", cardType: "monster", kind: "昆虫族", attribute: "地", level: 4, atk: 1200, def: 1400, rarity: "N" },
  { id: "vol6-great-moth", name: "グレート・モス", cardType: "monster", kind: "昆虫族", attribute: "地", level: 8, atk: 2600, def: 2500, rarity: "SE", effect: true },
  { id: "vol6-thousand-dragon", name: "千年竜", cardType: "monster", kind: "ドラゴン族", attribute: "風", level: 7, atk: 2400, def: 2000, rarity: "SE", fusion: true },
  { id: "vol6-lord-zemia", name: "ゼミアの神", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 4, atk: 1300, def: 1000, rarity: "N" },
  { id: "vol6-gatekeeper", name: "冥界の番人", cardType: "monster", kind: "戦士族", attribute: "地", level: 4, atk: 1000, def: 1200, rarity: "N" },
  { id: "vol6-protector-throne", name: "王座の守護者", cardType: "monster", kind: "戦士族", attribute: "地", level: 4, atk: 800, def: 1500, rarity: "N" },
  { id: "vol6-shadow-ghoul", name: "シャドウ・グール", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 5, atk: 1600, def: 1300, rarity: "SR", effect: true },
  { id: "vol6-giltia", name: "魔導騎士ギルティア", cardType: "monster", kind: "戦士族", attribute: "光", level: 5, atk: 1850, def: 1500, rarity: "N", fusion: true },
  { id: "vol6-gigatech-wolf", name: "ギガテック・ウルフ", cardType: "monster", kind: "機械族", attribute: "炎", level: 4, atk: 1200, def: 1400, rarity: "N" },
  { id: "vol6-shovel-crusher", name: "シャベル・クラッシャー", cardType: "monster", kind: "機械族", attribute: "地", level: 3, atk: 900, def: 1200, rarity: "N" },
  { id: "vol6-cyber-commander", name: "コマンダー", cardType: "monster", kind: "機械族", attribute: "闇", level: 2, atk: 750, def: 700, rarity: "N" },
  { id: "vol6-dice-armadillo", name: "ダイス・アルマジロ", cardType: "monster", kind: "機械族", attribute: "地", level: 5, atk: 1650, def: 1800, rarity: "N" },
  { id: "vol6-ice-water", name: "氷水", cardType: "monster", kind: "水族", attribute: "水", level: 3, atk: 1150, def: 900, rarity: "N" },
  { id: "vol6-sea-king-dragon", name: "海の竜王", cardType: "monster", kind: "海竜族", attribute: "水", level: 6, atk: 2000, def: 1700, rarity: "N" },
  { id: "vol6-kanikabuto", name: "カニカブト", cardType: "monster", kind: "水族", attribute: "水", level: 3, atk: 650, def: 900, rarity: "N" },
  { id: "vol6-bolt-escargot", name: "ボルト・エスカルゴ", cardType: "monster", kind: "雷族", attribute: "水", level: 5, atk: 1400, def: 1500, rarity: "N" },
  { id: "vol6-punished-eagle", name: "裁きの鷹", cardType: "monster", kind: "鳥獣族", attribute: "風", level: 6, atk: 2100, def: 1800, rarity: "N", fusion: true },
  { id: "vol6-air-eater", name: "エア・イーター", cardType: "monster", kind: "悪魔族", attribute: "風", level: 6, atk: 2100, def: 1600, rarity: "N" },
  { id: "vol6-burglar", name: "バーグラー", cardType: "monster", kind: "獣族", attribute: "地", level: 3, atk: 850, def: 800, rarity: "N" },
  { id: "vol6-hoshiningen", name: "スーパースター", cardType: "monster", kind: "天使族", attribute: "光", level: 2, atk: 500, def: 700, rarity: "R", effect: true },
  { id: "vol6-musician-king", name: "音楽家の帝王", cardType: "monster", kind: "魔法使い族", attribute: "光", level: 5, atk: 1750, def: 1500, rarity: "N", fusion: true },
  { id: "vol6-prisman", name: "プリズマン", cardType: "monster", kind: "岩石族", attribute: "光", level: 3, atk: 800, def: 1000, rarity: "N" },
  { id: "vol6-laughing-flower", name: "笑う花", cardType: "monster", kind: "植物族", attribute: "地", level: 2, atk: 900, def: 500, rarity: "N" },
  { id: "vol6-cannon-soldier", name: "キャノン・ソルジャー", cardType: "monster", kind: "機械族", attribute: "闇", level: 4, atk: 1400, def: 1300, rarity: "N", effect: true },
  { id: "vol6-muka-muka", name: "ムカムカ", cardType: "monster", kind: "岩石族", attribute: "地", level: 2, atk: 600, def: 300, rarity: "SR", effect: true },
  { id: "vol6-star-boy", name: "スター・ボーイ", cardType: "monster", kind: "水族", attribute: "水", level: 2, atk: 550, def: 500, rarity: "R", effect: true },
  { id: "vol6-milus-radiant", name: "ミリス・レディエント", cardType: "monster", kind: "獣族", attribute: "地", level: 1, atk: 300, def: 250, rarity: "SR", effect: true },
  { id: "vol6-flame-cerberus", name: "フレイム・ケルベロス", cardType: "monster", kind: "炎族", attribute: "炎", level: 6, atk: 2100, def: 1800, rarity: "N" },
  { id: "vol6-niwatori", name: "コケ", cardType: "monster", kind: "鳥獣族", attribute: "地", level: 3, atk: 900, def: 800, rarity: "N" },
  { id: "vol6-witch-black-forest", name: "黒き森のウィッチ", cardType: "monster", kind: "魔法使い族", attribute: "闇", level: 4, atk: 1100, def: 1200, rarity: "N", effect: true },
  { id: "vol6-tundra-scorpion", name: "ツンドラの大蠍", cardType: "monster", kind: "昆虫族", attribute: "地", level: 3, atk: 1100, def: 1000, rarity: "N" },
  { id: "vol6-little-chimera", name: "リトル・キメラ", cardType: "monster", kind: "獣族", attribute: "炎", level: 2, atk: 600, def: 550, rarity: "R", effect: true },
  { id: "vol6-violent-rain", name: "スコール", cardType: "monster", kind: "水族", attribute: "水", level: 4, atk: 1550, def: 800, rarity: "N" },
  { id: "vol6-tenderness", name: "テンダネス", cardType: "monster", kind: "天使族", attribute: "光", level: 3, atk: 700, def: 1400, rarity: "N" },
  { id: "vol6-bladefly", name: "ブレードフライ", cardType: "monster", kind: "昆虫族", attribute: "風", level: 2, atk: 600, def: 700, rarity: "R", effect: true },
  { id: "vol6-lady-faith", name: "ハイ・プリーステス", cardType: "monster", kind: "魔法使い族", attribute: "光", level: 3, atk: 1100, def: 800, rarity: "N" },
  { id: "vol6-nekogal-2", name: "キャット・レディ", cardType: "monster", kind: "獣戦士族", attribute: "地", level: 6, atk: 1900, def: 2000, rarity: "N" },
  { id: "vol6-witch-apprentice", name: "見習い魔女", cardType: "monster", kind: "魔法使い族", attribute: "闇", level: 2, atk: 550, def: 500, rarity: "R", effect: true },
  { id: "vol6-blue-winged-crown", name: "冠を戴く蒼き翼", cardType: "monster", kind: "鳥獣族", attribute: "風", level: 4, atk: 1600, def: 1200, rarity: "N" },
  { id: "vol6-polymerization", name: "融合", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "vol6-solemn-judgment", name: "神の宣告", cardType: "trap", kind: "カウンター罠", rarity: "UR" },
  { id: "vol6-magic-jammer", name: "マジック・ジャマー", cardType: "trap", kind: "カウンター罠", rarity: "UR" },
  { id: "vol6-seven-tools", name: "盗賊の七つ道具", cardType: "trap", kind: "カウンター罠", rarity: "UR" },
  { id: "vol6-horn-heaven", name: "昇天の角笛", cardType: "trap", kind: "カウンター罠", rarity: "UR" },
];
