import type { Card } from "./card-data";

// 2000年1月27日発売「Vol.7」全52種類。
// ノーマルレアのクリボーは、ゲーム内の共通レアリティ表現ではNとして扱う。
export const vol7Cards: Card[] = [
  { id: "vol7-arouane", name: "アルラウネ", cardType: "monster", kind: "植物族", attribute: "地", level: 3, atk: 800, def: 1000, rarity: "N" },
  { id: "vol7-ammonite", name: "アンモ・ナイト", cardType: "monster", kind: "水族", attribute: "水", level: 4, atk: 1000, def: 1200, rarity: "N" },
  { id: "vol7-undine", name: "ウンディーネ", cardType: "monster", kind: "水族", attribute: "水", level: 3, atk: 1100, def: 700, rarity: "N" },
  { id: "vol7-gluttonous-ghoul", name: "大食いグール", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 4, atk: 1600, def: 1200, rarity: "N" },
  { id: "vol7-crazy-fish", name: "クレイジー・フィッシュ", cardType: "monster", kind: "魚族", attribute: "水", level: 4, atk: 1600, def: 1200, rarity: "N" },
  { id: "vol7-centaur", name: "ケンタウロス", cardType: "monster", kind: "獣族", attribute: "地", level: 4, atk: 1300, def: 1550, rarity: "N" },
  { id: "vol7-toon-alligator", name: "トゥーン・アリゲーター", cardType: "monster", kind: "爬虫類族", attribute: "水", level: 4, atk: 800, def: 1600, rarity: "N" },
  { id: "vol7-hero-east", name: "東方の英雄", cardType: "monster", kind: "戦士族", attribute: "地", level: 3, atk: 1100, def: 1000, rarity: "N" },
  { id: "vol7-cursed-sword", name: "呪われし魔剣", cardType: "monster", kind: "戦士族", attribute: "闇", level: 4, atk: 1400, def: 800, rarity: "N" },
  { id: "vol7-prevent-rat", name: "プリヴェント・ラット", cardType: "monster", kind: "獣族", attribute: "地", level: 4, atk: 500, def: 2000, rarity: "N" },
  { id: "vol7-murder-circus-zombie", name: "マーダーサーカス・ゾンビ", cardType: "monster", kind: "アンデット族", attribute: "闇", level: 2, atk: 1350, def: 0, rarity: "N" },
  { id: "vol7-saggi", name: "闇・道化師のサギー", cardType: "monster", kind: "魔法使い族", attribute: "闇", level: 3, atk: 600, def: 1500, rarity: "N" },
  { id: "vol7-rainbow-fish", name: "レインボー・フィッシュ", cardType: "monster", kind: "魚族", attribute: "水", level: 4, atk: 1800, def: 800, rarity: "N" },
  { id: "vol7-red-ace", name: "レッド・エース", cardType: "monster", kind: "魔法使い族", attribute: "闇", level: 3, atk: 1000, def: 800, rarity: "N" },
  { id: "vol7-iron-heart", name: "アイアン・ハート", cardType: "monster", kind: "機械族", attribute: "闇", level: 5, atk: 1700, def: 1400, rarity: "N" },
  { id: "vol7-faceless-mage", name: "幻想師・ノー・フェイス", cardType: "monster", kind: "魔法使い族", attribute: "闇", level: 5, atk: 1200, def: 2200, rarity: "N" },
  { id: "vol7-mechanical-soldier", name: "機械の兵隊", cardType: "monster", kind: "機械族", attribute: "闇", level: 5, atk: 1500, def: 1700, rarity: "N" },
  { id: "vol7-giganto", name: "ギガント", cardType: "monster", kind: "機械族", attribute: "闇", level: 5, atk: 1700, def: 1800, rarity: "N" },
  { id: "vol7-giant-bird", name: "巨大な怪鳥", cardType: "monster", kind: "鳥獣族", attribute: "風", level: 6, atk: 2000, def: 1900, rarity: "N" },
  { id: "vol7-killer-machine", name: "キラー・マシーン", cardType: "monster", kind: "機械族", attribute: "闇", level: 5, atk: 1450, def: 1500, rarity: "N" },
  { id: "vol7-crashman", name: "クラッシュマン", cardType: "monster", kind: "獣族", attribute: "地", level: 5, atk: 1600, def: 1800, rarity: "N" },
  { id: "vol7-gate-keeper", name: "ゲート・キーパー", cardType: "monster", kind: "機械族", attribute: "闇", level: 5, atk: 1500, def: 1800, rarity: "N" },
  { id: "vol7-dark-chimera", name: "ダーク・キメラ", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 5, atk: 1610, def: 1460, rarity: "N" },
  { id: "vol7-pendulum-machine", name: "振り子刃の拷問機械", cardType: "monster", kind: "機械族", attribute: "闇", level: 6, atk: 1750, def: 2000, rarity: "N" },
  { id: "vol7-dark-dragon-jungle", name: "密林の黒竜王", cardType: "monster", kind: "ドラゴン族", attribute: "地", level: 6, atk: 2100, def: 1800, rarity: "N" },
  { id: "vol7-zanki", name: "鎧武者斬鬼", cardType: "monster", kind: "戦士族", attribute: "地", level: 5, atk: 1500, def: 1700, rarity: "N" },
  { id: "vol7-royal-guard", name: "ロイヤルガード", cardType: "monster", kind: "機械族", attribute: "地", level: 6, atk: 1900, def: 2200, rarity: "N" },
  { id: "vol7-launcher-spider", name: "ＴＭ－１ランチャースパイダー", cardType: "monster", kind: "機械族", attribute: "炎", level: 7, atk: 2200, def: 2500, rarity: "N" },
  { id: "vol7-dimensional-warrior", name: "異次元の戦士", cardType: "monster", kind: "戦士族", attribute: "地", level: 4, atk: 1200, def: 1000, rarity: "SR", effect: true },
  { id: "vol7-thunder-nyan-nyan", name: "雷仙人", cardType: "monster", kind: "雷族", attribute: "光", level: 4, atk: 1500, def: 1300, rarity: "N", effect: true },
  { id: "vol7-kuriboh", name: "クリボー", cardType: "monster", kind: "悪魔族", attribute: "闇", level: 1, atk: 300, def: 200, rarity: "N", effect: true },
  { id: "vol7-dark-elf", name: "ダーク・エルフ", cardType: "monster", kind: "魔法使い族", attribute: "闇", level: 4, atk: 2000, def: 800, rarity: "N", effect: true },
  { id: "vol7-sword-queen", name: "剣の女王", cardType: "monster", kind: "戦士族", attribute: "風", level: 3, atk: 900, def: 700, rarity: "R", effect: true },
  { id: "vol7-unhappy-maiden", name: "薄幸の美少女", cardType: "monster", kind: "魔法使い族", attribute: "光", level: 1, atk: 0, def: 100, rarity: "SR", effect: true },
  { id: "vol7-matango", name: "マタンゴ", cardType: "monster", kind: "戦士族", attribute: "地", level: 3, atk: 1250, def: 800, rarity: "N", effect: true },
  { id: "vol7-catapult-turtle", name: "カタパルト・タートル", cardType: "monster", kind: "水族", attribute: "水", level: 5, atk: 1000, def: 2000, rarity: "SR", effect: true },
  { id: "vol7-thunder-dragon", name: "サンダー・ドラゴン", cardType: "monster", kind: "雷族", attribute: "光", level: 5, atk: 1600, def: 1500, rarity: "R", effect: true },
  { id: "vol7-barbarian-1", name: "バーバリアン１号", cardType: "monster", kind: "戦士族", attribute: "地", level: 5, atk: 1550, def: 1800, rarity: "N", effect: true },
  { id: "vol7-barbarian-2", name: "バーバリアン２号", cardType: "monster", kind: "戦士族", attribute: "地", level: 5, atk: 1800, def: 1500, rarity: "N", effect: true },
  { id: "vol7-barrel-dragon", name: "リボルバー・ドラゴン", cardType: "monster", kind: "機械族", attribute: "闇", level: 7, atk: 2600, def: 2200, rarity: "UR", effect: true },
  { id: "vol7-twin-headed-thunder-dragon", name: "双頭の雷龍", cardType: "monster", kind: "雷族", attribute: "光", level: 7, atk: 2800, def: 2100, rarity: "UR", fusion: true },
  { id: "vol7-rabid-horseman", name: "ミノケンタウロス", cardType: "monster", kind: "獣戦士族", attribute: "地", level: 6, atk: 2000, def: 1700, rarity: "N", fusion: true },
  { id: "vol7-labyrinth-tank", name: "迷宮の魔戦車", cardType: "monster", kind: "機械族", attribute: "闇", level: 7, atk: 2400, def: 2400, rarity: "N", fusion: true },
  { id: "vol7-mecha-saurus", name: "メカ・ザウルス", cardType: "monster", kind: "機械族", attribute: "地", level: 5, atk: 1800, def: 1400, rarity: "N", fusion: true },
  { id: "vol7-tremendous-fire", name: "火炎地獄", cardType: "spell", kind: "通常魔法", rarity: "R" },
  { id: "vol7-stop-attack", name: "『攻撃』封じ", cardType: "spell", kind: "通常魔法", rarity: "N" },
  { id: "vol7-germ-infection", name: "細菌感染", cardType: "spell", kind: "装備魔法", rarity: "R" },
  { id: "vol7-paralyzing-potion", name: "しびれ薬", cardType: "spell", kind: "装備魔法", rarity: "R" },
  { id: "vol7-sword-deep-seated", name: "執念の剣", cardType: "spell", kind: "装備魔法", rarity: "N" },
  { id: "vol7-shield-sword", name: "右手に盾を左手に剣を", cardType: "spell", kind: "通常魔法", rarity: "UR" },
  { id: "vol7-robbin-goblin", name: "追い剥ぎゴブリン", cardType: "trap", kind: "永続罠", rarity: "SR" },
  { id: "vol7-mirror-force", name: "聖なるバリア －ミラーフォース－", cardType: "trap", kind: "通常罠", rarity: "SE" },
];
